#!/usr/bin/env python3
"""
Generate left/right Keyball61 ergonomic drafts from Ergohaven's
Sculpt_keycaps_v1.py.

Put this file beside Sculpt_keycaps_v1.py and run:
    python make_keyball61_sculpt_drafts_v3.py
"""

from pathlib import Path
import ast
import re
import sys

SRC = Path("Sculpt_keycaps_v1.py")

BASE_HEIGHTS = [
    [13.0, 11.0,  9.0,  9.0, 11.0, 13.0,  0.0],
    [10.4,  7.9,  5.9,  5.7,  7.9, 10.4,  0.0],
    [ 9.8,  7.3,  5.0,  5.0,  6.8,  9.3,  0.0],
    [12.0, 10.0,  8.0,  8.0,  9.5, 11.8, 13.8],
    [ 0.0,  0.0, 11.0, 11.0,  0.0,  0.0,  0.0],
]

# [Inference] First-pass ergonomic offsets in mm.
# Assumed mapping:
# col0 pinky, col1 pinky, col2 ring, col3 middle,
# col4 index, col5 index, col6 special/unused
LEFT_COLUMN_OFFSETS  = [5.0, 5.0, 2.0, 0.0, 0.0, 0.0, 0.0]
RIGHT_COLUMN_OFFSETS = [5.0, 5.0, 2.5, 0.0, 2.5, 2.5, 0.0]


def adjusted_heights(offsets):
    result = []
    for row in BASE_HEIGHTS:
        new_row = []
        for c, h in enumerate(row):
            new_row.append(0.0 if h == 0.0 else round(h + offsets[c], 2))
        result.append(new_row)
    return result


def matrix_block(matrix, hand):
    labels = ["row 0", "row 1", "row 2 / home-ish", "row 3", "row 4 / special"]
    lines = [
        f"# --- Keyball61 {hand} hand draft: finger-length compensation ---",
        "# [Inference] Trial geometry based on measured finger lengths.",
        "# Verify column mapping in CQ-Editor before printing the whole set.",
        "KEY_HEIGHT: List[List[Optional[float]]] = [",
    ]
    for label, row in zip(labels, matrix):
        vals = ", ".join(f"{x:.2f}" for x in row)
        lines.append(f"    [{vals}],  # {label}")
    lines.append("]")
    return "\n".join(lines)


def replace_key_height(text, hand, offsets):
    # Locate KEY_HEIGHT line.
    m = re.search(
        r'(?m)^KEY_HEIGHT\s*(?::\s*List\[List\[Optional\[float\]\]\])?\s*=',
        text
    )
    if not m:
        raise RuntimeError("Could not locate KEY_HEIGHT assignment.")

    # IMPORTANT: search for the matrix '[' AFTER the '=' so we do not
    # accidentally grab '[' from the type annotation.
    eq_idx = text.find("=", m.start(), m.end())
    open_idx = text.find("[", eq_idx)
    if open_idx == -1:
        raise RuntimeError("Could not locate opening '[' of KEY_HEIGHT value.")

    depth = 0
    end_idx = None
    for i in range(open_idx, len(text)):
        if text[i] == "[":
            depth += 1
        elif text[i] == "]":
            depth -= 1
            if depth == 0:
                end_idx = i + 1
                break
    if end_idx is None:
        raise RuntimeError("Could not locate end of KEY_HEIGHT matrix.")

    new = matrix_block(adjusted_heights(offsets), hand)
    return text[:m.start()] + new + text[end_idx:]


def replace_setting(text, name, value):
    # Supports either NAME = "..." or NAME: str = "..."
    pattern = rf'(?m)^{re.escape(name)}(?:\s*:\s*str)?\s*=\s*["\'][^"\']+["\']\s*$'
    new_text, count = re.subn(pattern, f'{name} = "{value}"', text, count=1)
    if count != 1:
        print(f"Warning: {name} assignment not found; left unchanged.")
    return new_text


def make_draft(source, hand, offsets):
    text = replace_key_height(source, hand, offsets)
    text = replace_setting(text, "MODE", hand)
    text = replace_setting(text, "QUALITY", "draft")

    banner = f"""# =============================================================================
# KEYBALL61 PERSONAL ERGONOMIC DRAFT — {hand.upper()} HAND
# Generated by make_keyball61_sculpt_drafts_v3.py
#
# First-test strategy:
#   * Ergohaven pitch/yaw: unchanged
#   * Ergohaven face tilt: unchanged
#   * Per-finger height: modified
# =============================================================================

"""
    result = banner + text

    # Syntax-check the COMPLETE generated Python file before writing it.
    ast.parse(result)
    return result


def main():
    print("Keyball61 Sculpt draft generator v3")
    print("-----------------------------------")

    if not SRC.exists():
        sys.exit(
            "ERROR: Sculpt_keycaps_v1.py not found.\n"
            "Place this generator in the same folder as Sculpt_keycaps_v1.py."
        )

    source = SRC.read_text(encoding="utf-8")
    ast.parse(source)
    print(f"Source syntax OK: {SRC.resolve()}")

    profiles = {
        "left": LEFT_COLUMN_OFFSETS,
        "right": RIGHT_COLUMN_OFFSETS,
    }

    for hand, offsets in profiles.items():
        result = make_draft(source, hand, offsets)
        out = Path(f"Sculpt_keycaps_keyball61_{hand}_draft.py")
        out.write_text(result, encoding="utf-8")
        print(f"Wrote + syntax checked: {out.resolve()}")

    print("\nDone. Both generated files passed Python syntax validation.")


if __name__ == "__main__":
    main()
