# =============================================================================
# KEYBALL61 PREVIEW + ENGRAVED LEGENDS — LEFT / RIGHT / BOTH
#
# Fixes:
#   * row/full preview no longer depends on PREVIEW_COL
#   * PREVIEW_COL is required only for PREVIEW_MODE = "key"
#   * engraving cutter again reaches the concave/dimpled surface
#   * cutter penetration is limited to avoid through-holes in closed letters
# =============================================================================

# =============================================================================
# KEYBALL61 PERSONAL FDM + ENGRAVED QWERTY — LEFT / RIGHT / BOTH
#
# [Inference] Draft FDM workflow:
#   * personalized KEY_HEIGHT retained
#   * original Sculpt KEY_ANGLES / KEY_FACE_TILT retained
#   * nominal top plane approximately leveled for printing
#   * NO CAD-generated supports; use slicer supports
#   * QWERTY alphabetic legends engraved into key tops
#
# Legend placement is an editable draft because the user's actual VIA/Remap
# keymap has not been supplied.
# =============================================================================

# =============================================================================
# KEYBALL61 FDM DRAFT — LEFT / RIGHT / BOTH
# Modified from the personal Sculpt draft.
#
# FDM_MODE=True:
#   * built-in sacrificial keycap/stem boots disabled
#   * lower wedge/tine/foot support geometry disabled
#   * body and MX stem start at Z=0
#   * original Sculpt KEY_ANGLES / KEY_FACE_TILT retained
#   * personalized KEY_HEIGHT retained
# =============================================================================

# =============================================================================
# KEYBALL61 PERSONAL ERGONOMIC DRAFT — LEFT / RIGHT / BOTH
# Generated by make_keyball61_sculpt_drafts.py
#
# First-test strategy:
#   * Ergohaven pitch/yaw: unchanged
#   * Ergohaven face tilt: unchanged
#   * Per-finger height: modified
#
# Do NOT print the whole set first.
# Verify the column mapping in CQ-Editor, then print a few test caps.
# =============================================================================

#!/usr/bin/env python3

# =============================================================================
# Sculpt – Parametric Keycap Generator by Ergohaven
# =============================================================================

import math
from contextlib import contextmanager
from dataclasses import dataclass
from functools import lru_cache
from typing import List, Optional, Tuple

import cadquery as cq
from OCP.BRepBuilderAPI import BRepBuilderAPI_GTransform, BRepBuilderAPI_Transform
from OCP.BRepFilletAPI import BRepFilletAPI_MakeFillet
from OCP.gp import (
    gp_Ax2, gp_Dir, gp_GTrsf, gp_Mat, gp_Pnt, gp_Trsf, gp_Vec, gp_XYZ,
)
from OCP.BRepAdaptor import BRepAdaptor_CompCurve
from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeEdge, BRepBuilderAPI_MakeWire
from OCP.GCPnts import GCPnts_UniformAbscissa
from OCP.GeomAPI import GeomAPI_Interpolate
from OCP.TColgp import TColgp_HArray1OfPnt
from OCP.TopAbs import TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID, TopAbs_WIRE
from OCP.TopExp import TopExp_Explorer
from OCP.TopoDS import TopoDS


# Keycap tuning parameters.
KC_BASE_WIDTH = 15.8                     # Base footprint width in mm.
KC_FACE_WIDTH = 7.5                      # Top surface width in mm.
KC_BASE_RADIUS = 1.125                   # Base corner radius in mm.
KC_FACE_RADIUS = 3.5                     # Top surface corner radius in mm.
KC_CAVITY_SCALE = 0.85                   # Inner cavity XY scale factor.
KC_SUPPORT_TOP_THIN = 0.5                # Thin support thickness near the top in mm.
KC_SUPPORT_ANGLE = 25.0                  # Default support wedge angle in degrees.
KC_SLICES = 30                           # Loft slice count.
KC_DIMPLE_INSET = -0.75                  # Dimple inset offset in mm.
KC_DIMPLE_TRANSITION_FILLET = 0.5        # Dimple seam softening radius in mm.
KC_TOP_THICKNESS_MIN = 1.0               # Minimum top shell thickness in mm.


# Stem tuning parameters.
STEM_BASE_HEIGHT = 3.6                   # Stem post height in mm.
STEM_BASE_SPACING = 11.0                 # Multi-post spacing in mm.
STEM_KEY_WIDTH = 18.0                    # Reference key width for stem placement.
STEM_BASE_LIFT = 0.0                     # Stem lift above the local base in mm.
STEM_WING_BREADTH = 4.1                  # Cross wing breadth in mm.
STEM_WING_THICKNESS = 1.17               # Cross wing thickness in mm.
STEM_ENTRY_FILLET_RADIUS = 0.0           # Switch-entry rim radius; unrelated to cap root. Keep 0 unless wanted.


# Keycap tuning parameters.
LAYOUT_UNIT = 19.05                      # Key pitch in mm.
LAYOUT_DIMPLE_DEPTH = 1.2                # Top dimple depth in mm.
DEFAULT_FACE_TILT = 0.0                  # Extra local face tilt in degrees.
KEYCAP_BOOT_HEIGHT = 3.0                 # Keycap boot height in mm.
STEM_BOOT_HEIGHT = 3.2                   # Stem boot height in mm.
MAX_KEY_HEIGHT = 7.0                     # Sweep-derived maximum height in mm.
MIN_KEY_HEIGHT = 4.0                     # Sweep-derived minimum height in mm.
SYMBOL_DEPTH = -3.25                     # Inner wall legend depth in mm.
LAYOUT_COLUMNS = 7                       # Matrix column count.
LAYOUT_ROWS = 5                          # Matrix row count.


# Matrix sweep angles as (pitch, yaw) in degrees.
KEY_ANGLES: List[List[Tuple[float, float]]] = [
    [(9.0, 5.5), (9.0, 6.5), (9.0, 2.5), (9.0, -2.5), (9.0, -7.5), (9.0, -7.5), (0.0, -0.0)],
    [(6.0, 6.0), (6.0, 7.0), (6.0, 2.5), (6.0, -2.5), (6.0, -7.5), (6.0, -7.5), (0.0, -0.0)],
    [(-3.0, 6.0), (-3.0, 7.0), (-3.0, 2.5), (-3.0, -2.5), (-3.0, -7.5), (-3.0, -7.5), (-0.0, -0.0)],
    [(-9.0, 5.5), (-9.0, 7.0), (-9.0, 2.5), (-9.0, -2.5), (-9.0, -7.5), (-9.0, -7.5), (-9.0, -8.0)],
    [(-0.0, 0.0), (-0.0, 0.0), (-8.0, 2.5), (-8.0, -2.5), (-0.0, -0.0), (-0.0, -0.0), (-0.0, -0.0)],
]


# Additional local top-surface tilt per key.
KEY_FACE_TILT: List[List[float]] = [
    [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 0.0],
    [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [-4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4.0],
    [0.0, 0.0, -4.0, -4.0, 0.0, 0.0, 0.0],
]


# --- Keyball61 left hand draft: finger-length compensation ---
# [Inference] Trial geometry based on measured finger lengths.
# Verify column mapping in CQ-Editor before printing the whole set.
KEY_HEIGHT: List[List[Optional[float]]] = [
    [18.00, 16.00, 11.00, 9.00, 11.00, 13.00, 0.00],  # row 0
    [15.40, 12.90, 7.90, 5.70, 7.90, 10.40, 0.00],  # row 1
    [14.80, 12.30, 7.00, 5.00, 6.80, 9.30, 0.00],  # row 2 / home-ish
    [17.00, 15.00, 10.00, 8.00, 9.50, 11.80, 13.80],  # row 3
    [13.00, 12.00, 13.00, 11.00, 10.50, 0.00, 0.00],  # row 4 left: blank, [, ], blank, Alt
]


# Keycap tuning parameters.
THUMB_HEIGHTS: Tuple[float, float, float, float] = (9.0, 10.5, 12.0, 0.0)  # Legacy/default.
THUMB_HEIGHTS_LEFT: Tuple[float, float, float, float] = (9.0, 10.5, 12.0, 0.0)   # MO, Space, Backspace.
THUMB_HEIGHTS_RIGHT: Tuple[float, float, float, float] = (9.0, 10.5, 0.0, 0.0)   # Enter, MODown; then trackball.


# Keycap tuning parameters.
THUMB_SWEEP = [(12, 10.0), (14, 7.0), (16, 4.0), (0, 0.0)]                     # Thumb sweep angles as (pitch, yaw).


# Keycap tuning parameters.
THUMB_FACE_TILT = [8.0, 10.0, 12.0, 0.0]                                       # Extra local thumb face tilt in degrees.


MODE = "left"
QUALITY = "draft"
INCLUDE_FN_ROW = False

# FDM printing mode:
# - disables Ergohaven's built-in sacrificial resin-style support geometry
# - approximately levels the nominal top-face plane to the build plate
# - creates NO CAD support structures; let the slicer generate supports
FDM_MODE = True
FDM_FLIP_TOP_DOWN = True
#FDM_FLIP_TOP_DOWN = False
FDM_LEVEL_TOP = True

# Top surface are flat, more FDM friendly
TOP_SURFACE_MODE = "flat"
# TOP_SURFACE_MODE = "concave"
# Top-surface engraved legends.
TOP_LEGENDS = True

# Optional tactile homing bump on the F/J-position keycaps.
# Disable for face-down FDM printing so the flat top lies fully on the bed.
HOMING_BUMP_ENABLED = False

# [Inference] First-pass legend settings:
# FDM gets a larger/bolder/shallower engraving for a 0.4 mm nozzle.
# Resin keeps a finer engraving.
if FDM_MODE:
    TOP_LEGEND_FONT = "DejaVu Sans:style=Bold"
    TOP_LEGEND_SIZE = 5.2
    TOP_LEGEND_DEPTH = 0.30
else:
    TOP_LEGEND_FONT = "Arial"
    TOP_LEGEND_SIZE = 4.2
    TOP_LEGEND_DEPTH = 0.40

# Fast preview controls for CQ-Editor.
# "full" = whole hand
# "row"  = one matrix row
# "key"  = one matrix key
# "thumbs" = thumb cluster only
PREVIEW_MODE = "full"
PREVIEW_ROW = 0
# PREVIEW_COL = 3 only when key preview is desired. Otherwise, it can be None.

# Only used when PREVIEW_MODE == "key".
# It can be None for "row" or "full".
PREVIEW_COL = None

# -----------------------------------------------------------------------------
# Stem-root fillet options
# -----------------------------------------------------------------------------
STEM_CAP_ROOT_RADIUS = 0.0              # Experimental stem-root fillet disabled.
STEM_CAP_ROOT_RADIUS_MIN = 0.20         # Smallest allowed fallback radius in mm.
STEM_CAP_ROOT_RADIUS_STEP = 0.10        # Radius decrement per retry in mm.
_QUALITY_PRESETS = {
    "draft":      {"slices": 8},
    "production": {"slices": 30},
}


def _trace(_name: str):
    def deco(fn):
        return fn
    return deco


@contextmanager
def _trace_block(_name: str):
    yield


def _finalize_runtime_notes() -> None:
    return None


@dataclass(frozen=True)
class KeycapConfig:

    base_width: float = KC_BASE_WIDTH
    face_width: float = KC_FACE_WIDTH
    base_r: float = KC_BASE_RADIUS
    face_r: float = KC_FACE_RADIUS
    cavity: float = KC_CAVITY_SCALE
    support_top_thin: float = KC_SUPPORT_TOP_THIN
    support_angle: float = KC_SUPPORT_ANGLE
    slices: int = KC_SLICES
    dimple_inset: float = KC_DIMPLE_INSET
    dimple_transition_fillet: float = KC_DIMPLE_TRANSITION_FILLET
    top_thickness_min: float = KC_TOP_THICKNESS_MIN


@dataclass(frozen=True)
class StemConfig:

    base_height: float = STEM_BASE_HEIGHT
    base_spacing: float = STEM_BASE_SPACING
    key_width: float = STEM_KEY_WIDTH
    base_lift: float = STEM_BASE_LIFT
    wing_breadth: float = STEM_WING_BREADTH
    wing_thickness: float = STEM_WING_THICKNESS


@dataclass(frozen=True)
class LayoutConfig:

    unit: float = LAYOUT_UNIT
    dimple_depth: float = LAYOUT_DIMPLE_DEPTH
    face_tilt: float = DEFAULT_FACE_TILT
    boot_keycap: float = KEYCAP_BOOT_HEIGHT
    boot_stem: float = STEM_BOOT_HEIGHT
    max_height: float = MAX_KEY_HEIGHT
    min_height: float = MIN_KEY_HEIGHT
    thumb_heights: Tuple[float, float, float, float] = THUMB_HEIGHTS
    symbol_depth: float = SYMBOL_DEPTH
    columns: int = LAYOUT_COLUMNS
    rows: int = LAYOUT_ROWS

    @property
    def thumb_height(self) -> float:
        return self.thumb_heights[0]


LEGEND_BASE_WIDTH = 5.0
LEGEND_DEPTH = 0.5
LEGEND_FIT_WIDTH = 10.0
LEGEND_FONT = "Arial"
LEGEND_CAVITY_SCALE = 0.95


@dataclass(frozen=True)
class LegendConfig:

    base_width: float = LEGEND_BASE_WIDTH
    depth: float = LEGEND_DEPTH
    fit_width: float = LEGEND_FIT_WIDTH
    font: str = LEGEND_FONT
    legend_cavity: float = LEGEND_CAVITY_SCALE


KC = KeycapConfig()
SC = StemConfig()
LC = LayoutConfig()
LG = LegendConfig()


def _apply_dimple_to_wire(wire: cq.Wire, dimple_depth: float) -> cq.Wire:


    try:
        adaptor = BRepAdaptor_CompCurve(wire.wrapped)
        n_pts = 64
        discretizer = GCPnts_UniformAbscissa(adaptor, n_pts)
        if not discretizer.IsDone() or discretizer.NbPoints() < 4:
            return wire

        bbox = wire.BoundingBox()
        cx = (bbox.xmin + bbox.xmax) / 2.0
        cy = (bbox.ymin + bbox.ymax) / 2.0
        max_dist = math.sqrt((bbox.xmax - cx) ** 2 + (bbox.ymax - cy) ** 2)
        if max_dist < 0.001:
            return wire

        n = discretizer.NbPoints()
        pts = TColgp_HArray1OfPnt(1, n)
        for i in range(1, n + 1):
            pnt = adaptor.Value(discretizer.Parameter(i))
            x, y, z = pnt.X(), pnt.Y(), pnt.Z()
            dist = math.sqrt((x - cx) ** 2 + (y - cy) ** 2)
            ratio = dist / max_dist
            dz = -dimple_depth * (1.0 - ratio * ratio)
            pts.SetValue(i, gp_Pnt(x, y, z + dz))

        interp = GeomAPI_Interpolate(pts, True, 1e-6)
        interp.Perform()
        if not interp.IsDone():
            return wire

        edge = BRepBuilderAPI_MakeEdge(interp.Curve()).Edge()
        return cq.Wire(BRepBuilderAPI_MakeWire(edge).Wire())
    except Exception:
        return wire


def _sign(x: float) -> float:

    return (1.0 if x > 0 else (-1.0 if x < 0 else 0.0))


def translate_solid(solid: cq.Solid, dx: float, dy: float, dz: float) -> cq.Solid:

    if dx == 0.0 and dy == 0.0 and dz == 0.0:
        return solid
    t = gp_Trsf()
    t.SetTranslation(gp_Vec(dx, dy, dz))
    return cq.Solid(BRepBuilderAPI_Transform(solid.wrapped, t, True).Shape())


def scale_solid(solid: cq.Solid, factor: float) -> cq.Solid:

    t = gp_Trsf()
    t.SetScale(gp_Pnt(0, 0, 0), factor)
    return cq.Solid(BRepBuilderAPI_Transform(solid.wrapped, t, True).Shape())


def scale_solid_about(solid: cq.Solid, factor: float,
                      origin: Tuple[float, float, float]) -> cq.Solid:

    ox, oy, oz = origin
    t = gp_Trsf()
    t.SetScale(gp_Pnt(ox, oy, oz), factor)
    return cq.Solid(BRepBuilderAPI_Transform(solid.wrapped, t, True).Shape())


def rotate_solid(solid: cq.Solid, rx: float, ry: float, rz: float,
                 cx: float = 0.0, cy: float = 0.0, cz: float = 0.0) -> cq.Solid:


    if abs(rx) < 1e-6 and abs(ry) < 1e-6 and abs(rz) < 1e-6:
        return solid

    t_to_origin = gp_Trsf()
    t_to_origin.SetTranslation(gp_Vec(-cx, -cy, -cz))
    t_back = gp_Trsf()
    t_back.SetTranslation(gp_Vec(cx, cy, cz))
    rot = gp_Trsf()
    if abs(rz) > 1e-6:
        rz_t = gp_Trsf()
        rz_t.SetRotation(gp_Ax2(gp_Pnt(), gp_Dir(0, 0, 1)).Axis(), math.radians(rz))
        rot.Multiply(rz_t)
    if abs(ry) > 1e-6:
        ry_t = gp_Trsf()
        ry_t.SetRotation(gp_Ax2(gp_Pnt(), gp_Dir(0, 1, 0)).Axis(), math.radians(ry))
        rot.Multiply(ry_t)
    if abs(rx) > 1e-6:
        rx_t = gp_Trsf()
        rx_t.SetRotation(gp_Ax2(gp_Pnt(), gp_Dir(1, 0, 0)).Axis(), math.radians(rx))
        rot.Multiply(rx_t)
    combined = gp_Trsf()
    combined.Multiply(t_back)
    combined.Multiply(rot)
    combined.Multiply(t_to_origin)
    return cq.Solid(BRepBuilderAPI_Transform(solid.wrapped, combined, True).Shape())


def _compose_trsf(rx: float, ry: float, rz: float,
                  tx: float, ty: float, tz: float) -> gp_Trsf:

    trsf_rx = gp_Trsf()
    trsf_ry = gp_Trsf()
    trsf_rz = gp_Trsf()
    if abs(rx) > 1e-4:
        trsf_rx.SetRotation(gp_Ax2(gp_Pnt(), gp_Dir(1, 0, 0)).Axis(), math.radians(rx))
    if abs(ry) > 1e-4:
        trsf_ry.SetRotation(gp_Ax2(gp_Pnt(), gp_Dir(0, 1, 0)).Axis(), math.radians(ry))
    if abs(rz) > 1e-4:
        trsf_rz.SetRotation(gp_Ax2(gp_Pnt(), gp_Dir(0, 0, 1)).Axis(), math.radians(rz))
    combined = gp_Trsf()
    combined.Multiply(trsf_rz)
    combined.Multiply(trsf_ry)
    combined.Multiply(trsf_rx)
    t = gp_Trsf()
    t.SetTranslation(gp_Vec(tx, ty, tz))
    combined.Multiply(t)
    return combined


def position_wire(wire: cq.Wire,
                  pos: Tuple[float, float, float],
                  rot: Tuple[float, float, float]) -> cq.Wire:

    trsf = _compose_trsf(rot[0], rot[1], rot[2], pos[0], pos[1], pos[2])
    return cq.Wire(BRepBuilderAPI_Transform(wire.wrapped, trsf, True).Shape())


def _transform_solid_with_trsf(solid: cq.Solid, trsf: gp_Trsf) -> cq.Solid:

    return cq.Solid(BRepBuilderAPI_Transform(solid.wrapped, trsf, True).Shape())


def _step(n: int, i: int) -> float:

    half = (n - 1) * 0.5
    return (i - half) / half if half != 0 else 0.0


def _sin_extend(a: float) -> float:

    if abs(a) > 90:
        return round(a / 90.0) + math.sin(math.radians(a % 90))
    return math.sin(math.radians(a))


def _asin_extend(r: float) -> float:

    if abs(r) > 1:
        return 90.0 * round(r) + math.degrees(math.asin(r % 1))
    return math.degrees(math.asin(r))


def _bias_ratio(a: float, s: float) -> float:

    if a == 0 or s == 0:
        return 1.0
    if abs(a) > abs(s):
        return abs(s / a) * _sign(s)
    return abs(a / s) * _sign(s)


def _bias_degrees(r: float, a: float, s: float) -> float:

    mag = abs(s * _bias_ratio(a, s))
    return mag * _sign(r) if abs(r * a) > abs(s) else mag * _sign(s)


def _ratio_range(a: float, s: float) -> float:

    return abs(a) + abs(s)


def _ratio_degrees(r: float, a: float, s: float) -> float:

    return _asin_extend(r) * (_ratio_range(a, s) / 90.0) + _bias_degrees(r, a, s)


def _ratio_sin(r: float, e: float = 1.0, a: float = 0.0, s: float = 0.0) -> float:


    rd = _ratio_degrees(r, a, s)
    se = _sin_extend(rd)
    return abs(se) ** e * _sign(r)


def _step_smooth_2(n: int, i: int) -> Tuple[int, int, int]:

    if i == 0:
        return (0, 0, 0)
    if i == n - 1:
        return (n - 1, n - 1, n - 1)
    return (i - 1, i, i + 1)


def _step_angle(n: int, a: float, s: float, i: int) -> float:

    return -_ratio_sin(_step(n, i), 1.0, a, s)


def _step_height(n: int, a: float, s: float, i: int) -> float:

    return abs(_ratio_sin(_step(n, i), 1.0, a, s))


def _step_angle_smoothed(n: int, a: float, s: float, i: int) -> float:

    p = _step_smooth_2(n, i)
    return (_step_angle(n, a, s, p[0]) * 0.33
            + _step_angle(n, a, s, p[1]) * 0.33
            + _step_angle(n, a, s, p[2]) * 0.33)


def _step_height_smoothed(n: int, a: float, s: float, i: int) -> float:

    p = _step_smooth_2(n, i)
    return (_step_height(n, a, s, p[0]) * 0.25
            + _step_height(n, a, s, p[1]) * 0.5
            + _step_height(n, a, s, p[2]) * 0.25)


def single_axis_sweep(height: Tuple[float, float], sweep_angle: float,
                      sweep_shift: float, slices: int) -> List[Tuple[float, float]]:

    result: List[Tuple[float, float]] = []
    for i in range(slices):
        ang = _step_angle_smoothed(slices, sweep_angle, sweep_shift, i) * sweep_angle
        h = (_step_height_smoothed(slices, sweep_angle, sweep_shift, i)
             * (height[0] - height[1]) + height[1])
        result.append((ang, h))
    return result


def dual_axis_sweep(height: Tuple[float, float],
                    sweep_angle: Tuple[float, float],
                    sweep_shift: Tuple[float, float],
                    slices: Tuple[int, int]) -> list:


    axis_a = single_axis_sweep(height, sweep_angle[0], sweep_shift[0], slices[0])
    axis_b = single_axis_sweep(height, sweep_angle[1], sweep_shift[1], slices[1])
    design = []
    for a_ang, a_h in axis_a:
        col = []
        for b_ang, b_h in axis_b:
            ax = a_ang * 0.9 + abs(b_ang) * 0.1 * _sign(a_ang)
            ay = b_ang * 0.9 + abs(a_ang) * 0.1 * _sign(b_ang)
            ch = height[1] + (a_h + b_h - height[1] * 2)
            col.append(((ax, ay), ch))
        design.append(col)
    return design


def sweep_design(lc: LayoutConfig = LC) -> list:

    return dual_axis_sweep(
        height=(lc.max_height, lc.min_height),
        sweep_angle=(30.0, 30.0),
        sweep_shift=(0.0, -22.5),
        slices=(lc.columns, lc.rows),
    )


def _with_bottom_inset_bevel(bevel_slices: int, rate: float):

    def fn(i: int) -> float:
        if bevel_slices > 0 and i < bevel_slices:
            return 1.0 - (bevel_slices - i) / bevel_slices * rate
        return 1.0
    return fn


def _with_bottom_outset_bevel(bevel_slices: int, rate: float):

    def fn(i: int) -> float:
        if bevel_slices > 0 and i < bevel_slices:
            return 1.0 + (bevel_slices - i) / bevel_slices * rate
        return 1.0
    return fn


def _with_round_off(num_slices: int, angle: float):

    def fn(i: int) -> float:
        denom = max(num_slices - 1, 1)
        c = math.cos(math.radians(i / denom * angle))
        return max((1.0 + c * c) * 0.5, 0.001)
    return fn


def _with_round_off_2nd(num_slices: int, angle: float):

    ro = _with_round_off(num_slices, angle)
    def fn(i: int) -> float:
        inner_angle = angle - angle * ro(i)
        ro2 = _with_round_off(num_slices, inner_angle)
        return max(ro2(i), 0.001)
    return fn


@lru_cache(maxsize=None)
def compute_angle_index(num_slices: int) -> List[Tuple[float, float]]:


    sa = 90.0 / num_slices
    result: List[Tuple[float, float]] = []
    for i in range(num_slices + 1):
        t = i / num_slices if num_slices > 0 else 0.0
        pm = pow(t, 0.0625) if t > 0 else 0.0
        arg = sa * i * pm
        result.append((math.sin(math.radians(arg)), math.cos(math.radians(arg))))
    return result


def adjust_offsets(i: int, offsets: Tuple[float, float, float],
                   ai: List[Tuple[float, float]]) -> Tuple[float, float, float]:

    s, c = ai[i]
    return (offsets[0] - offsets[0] * c,
            offsets[1] - offsets[1] * c,
            offsets[2] * s)


def adjust_angles(i: int, angles: Tuple[float, float, float],
                  ai: List[Tuple[float, float]]) -> Tuple[float, float, float]:

    s, c = ai[i]
    return (angles[0] * s, angles[1] * s, angles[2] - angles[2] * c)


def _face_tilt_blend(i: int, n: int, start_ratio: float = 0.55) -> float:

    if n <= 0:
        return 1.0
    t = i / n
    if t <= start_ratio:
        return 0.0
    u = (t - start_ratio) / (1.0 - start_ratio)
    return u * u * (3.0 - 2.0 * u)


def _point_to_local_frame(point: Tuple[float, float, float],
                          origin: Tuple[float, float, float],
                          rot: Tuple[float, float, float]) -> Tuple[float, float, float]:

    x = point[0] - origin[0]
    y = point[1] - origin[1]
    z = point[2] - origin[2]

    rz = math.radians(-rot[2])
    cz, sz = math.cos(rz), math.sin(rz)
    x, y = x * cz - y * sz, x * sz + y * cz

    ry = math.radians(-rot[1])
    cy, sy = math.cos(ry), math.sin(ry)
    x, z = x * cy + z * sy, -x * sy + z * cy

    rx = math.radians(-rot[0])
    cx, sx = math.cos(rx), math.sin(rx)
    y, z = y * cx - z * sx, y * sx + z * cx

    return x, y, z


def _di_slice(i: int, a: float, b: float, num_slices: int) -> float:

    c = math.cos(math.radians(90.0 / num_slices * i))
    return (b + c * (a - b)) if a > b else (b - c * (b - a))


def r_slice(i: int, r: Tuple[float, float], n: int) -> float:

    return _di_slice(i, r[0], r[1], n)


def w_slice(i: int, w: Tuple[float, float], n: int) -> float:

    return _di_slice(i, w[0], w[1], n)


@lru_cache(maxsize=None)
def surface_scales(n: int) -> List[float]:

    rounding = _with_round_off_2nd(n, 75.0)
    bevel = _with_bottom_inset_bevel(round(n * 0.125), 0.005)
    return [bevel(i) * rounding(i) for i in range(n + 1)]


@lru_cache(maxsize=None)
def cavity_scales(n: int, cavity: float) -> List[float]:

    rounding = _with_round_off_2nd(n, 90.0)
    bev_a = _with_bottom_outset_bevel(round(n * 0.65), 0.005 * cavity)
    bev_b = _with_bottom_inset_bevel(round(n * 0.125), 0.005 * cavity)
    return [bev_a(i) * bev_b(i) * pow(rounding(i), 1.5) for i in range(n + 1)]


def make_rounded_rect_wire(w: float, h: float, r: float) -> cq.Wire:


    tw = w + 2.0 * r
    th = h + 2.0 * r
    cr = min(r, tw / 2.0, th / 2.0)
    if cr < 0.001:
        cr = 0.001
    sketch = cq.Sketch().rect(tw, th).vertices().fillet(cr)
    return sketch._faces.Wires()[0]


def make_profile_wire(i: int, kc: KeycapConfig, n: int,
                      unit: float, sf: float) -> cq.Wire:


    ri = r_slice(i, (kc.base_r, kc.face_r), n) * sf
    wi = w_slice(i, (kc.base_width, kc.face_width), n) * sf
    if ri < 0.001:
        ri = 0.001
    if wi < 0.01:
        wi = 0.01

    if abs(unit - 1.0) < 0.01:
        return make_rounded_rect_wire(wi, wi, ri)


    d1 = kc.base_width + kc.base_r * 2.0
    x_off = d1 * (unit - 1.0) / 2.0 * sf
    tw = wi + 2.0 * ri + 2.0 * x_off
    th = wi + 2.0 * ri
    cr = min(ri, tw / 2.0 - 0.001, th / 2.0 - 0.001)
    if cr < 0.001:
        cr = 0.001
    sketch = cq.Sketch().rect(tw, th).vertices().fillet(cr)
    return sketch._faces.Wires()[0]


@_trace("build_loft")
def build_loft(kc: KeycapConfig, n: int,
               face_offset: Tuple[float, float, float],
               face_angle: Tuple[float, float, float],
               unit: float, scales: List[float],
               z_base: float = 0.0,
               dimple_depth: float = 0.0,
               face_tilt: float = 0.0) -> cq.Solid:


    ai = compute_angle_index(n)
    wires: List[cq.Wire] = []
    for i in range(n + 1):
        sf = max(scales[i], 0.001)
        wire = make_profile_wire(i, kc, n, unit, sf)

        if i == n and dimple_depth > 0:
            wire = _apply_dimple_to_wire(wire, dimple_depth)
        off = adjust_offsets(i, face_offset, ai)
        ang = adjust_angles(i, face_angle, ai)
        if abs(face_tilt) > 1e-6:
            ang = (ang[0] + face_tilt * _face_tilt_blend(i, n), ang[1], ang[2])
        pos = (off[0], off[1], off[2] + z_base)
        wires.append(position_wire(wire, pos, ang))

    try:
        return cq.Solid.makeLoft(wires, ruled=False)
    except Exception:
        return cq.Solid.makeLoft(wires, ruled=True)


@_trace("keycap_body")
def keycap_body(kc: KeycapConfig, n: int,
                face_offset: Tuple[float, float, float],
                face_angle: Tuple[float, float, float],
                unit: float = 1.0,
                z_base: float = 0.0,
                dimple_depth: float = 0.0,
                face_tilt: float = 0.0,
                cavity_solid: Optional[cq.Solid] = None,
                inner_label_solids: Optional[List[cq.Solid]] = None) -> cq.Solid:


    with _trace_block("keycap_body.surface_loft"):
        surf = build_loft(kc, n, face_offset, face_angle, unit,
                          surface_scales(n), z_base, face_tilt=face_tilt)
    if dimple_depth > 0:
        try:
            with _trace_block("keycap_body.dimple_build"):
                dimple = make_dimple(kc, n, face_offset, face_angle,
                                     dimple_depth, unit, z_base, face_tilt=face_tilt)
            if dimple is not None:
                with _trace_block("keycap_body.dimple_cut"):
                    surf_cut = (cq.Workplane("XY").add(surf)
                                .cut(cq.Workplane("XY").add(dimple))
                                .solids().vals())
                if surf_cut:
                    with _trace_block("keycap_body.dimple_soften"):
                        surf = _soften_dimple_transition(
                            surf_cut[0], kc.dimple_transition_fillet,
                            kc, n, face_offset, face_angle, unit, z_base,
                            face_tilt=face_tilt, footprint_scale=1.0)
        except Exception:
            pass

    cav_scaled = cavity_solid
    if cav_scaled is None:
        with _trace_block("keycap_body.cavity_build_on_demand"):
            cav_scaled = build_cavity_solid(kc, n, face_offset, face_angle,
                                            unit, z_base, dimple_depth=dimple_depth,
                                            face_tilt=face_tilt)
    if cav_scaled is None:
        with _trace_block("keycap_body.cavity_fallback_loft"):
            cav = build_loft(kc, n, face_offset, face_angle, unit,
                             cavity_scales(n, kc.cavity), z_base,
                             face_tilt=face_tilt)
            cav_scaled = scale_solid_about(cav, kc.cavity, (0.0, 0.0, z_base))

    if inner_label_solids:
        with _trace_block("keycap_body.label_trim"):
            try:
                with _trace_block("keycap_body.label_compound"):
                    if len(inner_label_solids) == 1:
                        label_tool = inner_label_solids[0]
                    else:
                        label_tool = cq.Compound.makeCompound(inner_label_solids)

                with _trace_block("keycap_body.label_intersect_batch"):
                    text_in_cav = (cq.Workplane("XY").add(cav_scaled)
                                   .intersect(cq.Workplane("XY").add(label_tool))
                                   .solids().vals())

                if text_in_cav:
                    with _trace_block("keycap_body.label_cut_batch"):
                        if len(text_in_cav) == 1:
                            cut_tool = text_in_cav[0]
                        else:
                            cut_tool = cq.Compound.makeCompound(text_in_cav)

                        cav_trimmed = (cq.Workplane("XY").add(cav_scaled)
                                       .cut(cq.Workplane("XY").add(cut_tool))
                                       .solids().vals())
                        if cav_trimmed:
                            cav_scaled = cav_trimmed[0]
            except Exception as _e:
                print(f"[keycap_body] emboss solid failed: {_e}")

    try:
        with _trace_block("keycap_body.final_cut"):
            wp = cq.Workplane("XY").add(surf).cut(cq.Workplane("XY").add(cav_scaled))
            solids = wp.solids().vals()
            return solids[0] if solids else surf
    except Exception:
        return surf


@_trace("build_cavity_solid")
def build_cavity_solid(kc: KeycapConfig, n: int,
                       face_offset: Tuple[float, float, float],
                       face_angle: Tuple[float, float, float],
                       unit: float, z_base: float,
                       dimple_depth: float = 0.0,
                       face_tilt: float = 0.0) -> Optional[cq.Solid]:

    try:
        with _trace_block("build_cavity_solid.loft"):
            cav = build_loft(kc, n, face_offset, face_angle, unit,
                             cavity_scales(n, kc.cavity), z_base,
                             face_tilt=face_tilt)
            cav_scaled = scale_solid_about(cav, kc.cavity, (0.0, 0.0, z_base))
        if dimple_depth > 0:
            with _trace_block("build_cavity_solid.dimple_build"):
                dimple = make_dimple(kc, n, face_offset, face_angle,
                                     dimple_depth, unit, z_base, face_tilt=face_tilt)
            if dimple is not None:
                with _trace_block("build_cavity_solid.dimple_cut"):
                    dimple_scaled = scale_solid_about(dimple, kc.cavity, (0.0, 0.0, z_base))
                    cav_cut = (cq.Workplane("XY").add(cav_scaled)
                               .cut(cq.Workplane("XY").add(dimple_scaled))
                               .solids().vals())
                if cav_cut:
                    with _trace_block("build_cavity_solid.dimple_soften"):
                        cav_scaled = _soften_dimple_transition(
                            cav_cut[0], kc.dimple_transition_fillet * kc.cavity,
                            kc, n, face_offset, face_angle, unit, z_base,
                            face_tilt=face_tilt, footprint_scale=kc.cavity)
        with _trace_block("build_cavity_solid.min_top_thickness"):
            cav_scaled = _apply_min_top_thickness(cav_scaled, kc, n, face_offset)
        return cav_scaled
    except Exception:
        return None


@_trace("make_dimple")
def make_dimple(kc: KeycapConfig, n: int,
                face_offset: Tuple[float, float, float],
                face_angle: Tuple[float, float, float],
                dimple_depth: float,
                unit: float = 1.0,
                z_base: float = 0.0,
                face_tilt: float = 0.0) -> Optional[cq.Solid]:


    dimple_size = (kc.face_width + kc.face_r * 2.0) * 1.125
    sphere_d = dimple_size - kc.dimple_inset * 2.0
    sphere_r = sphere_d / 2.0
    if sphere_r < 0.1 or dimple_size < 0.01:
        return None

    z_sc = dimple_depth / (dimple_size * 0.5)
    z_tr = dimple_size * 0.5 * (dimple_depth / dimple_size)
    semi_c = sphere_r * abs(z_sc)

    n_lat = 48
    eps = 0.012
    wires: List[cq.Wire] = []
    for i in range(n_lat + 1):
        t = i / n_lat
        theta = (-math.pi / 2 + eps) + (math.pi - 2 * eps) * t
        r = sphere_r * math.cos(theta)
        z = semi_c * math.sin(theta) + z_tr
        wires.append(cq.Wire.makeCircle(r, cq.Vector(0, 0, z), cq.Vector(0, 0, 1)))

    try:
        ellipsoid = cq.Solid.makeLoft(wires, ruled=False)
    except Exception:
        try:
            ellipsoid = cq.Solid.makeLoft(wires, ruled=True)
        except Exception:
            return None

    ai = compute_angle_index(n)
    off = adjust_offsets(n, face_offset, ai)
    ang = adjust_angles(n, face_angle, ai)
    if abs(face_tilt) > 1e-6:
        ang = (ang[0] + face_tilt, ang[1], ang[2])
    pos = (off[0], off[1], off[2] + z_base)
    trsf = _compose_trsf(ang[0], ang[1], ang[2], pos[0], pos[1], pos[2])
    return cq.Solid(BRepBuilderAPI_Transform(ellipsoid.wrapped, trsf, True).Shape())


@_trace("_soften_dimple_transition")
def _soften_dimple_transition(solid: cq.Solid, radius: float,
                              kc: KeycapConfig,
                              n: int,
                              face_offset: Tuple[float, float, float],
                              face_angle: Tuple[float, float, float],
                              unit: float,
                              z_base: float,
                              face_tilt: float = 0.0,
                              footprint_scale: float = 1.0) -> cq.Solid:

    if radius <= 0:
        return solid
    try:
        ai = compute_angle_index(n)
        off = adjust_offsets(n, face_offset, ai)
        ang = adjust_angles(n, face_angle, ai)
        if abs(face_tilt) > 1e-6:
            ang = (ang[0] + face_tilt, ang[1], ang[2])

        top_origin = (off[0], off[1], off[2] + z_base)
        face_trsf = _compose_trsf(ang[0], ang[1], ang[2], top_origin[0], top_origin[1], top_origin[2])
        local_solid = _transform_solid_with_trsf(solid, face_trsf.Inverted())

        bb = local_solid.BoundingBox()
        top_band = max(radius * 4.0, 0.8)
        margin = max(radius * 1.5, 0.35)
        max_full_x = (bb.xmax - bb.xmin) - margin
        max_full_y = (bb.ymax - bb.ymin) - margin
        if max_full_x <= 0.1 or max_full_y <= 0.1:
            return solid

        mk = BRepFilletAPI_MakeFillet(local_solid.wrapped)
        added = 0
        for e in local_solid.Edges():
            ebb = e.BoundingBox()
            ex = ebb.xmax - ebb.xmin
            ey = ebb.ymax - ebb.ymin
            if ebb.zmax < bb.zmax - top_band:
                continue
            if ex < 0.8 and ey < 0.8:
                continue
            if ex >= max_full_x or ey >= max_full_y:
                continue
            try:
                mk.Add(radius, e.wrapped)
                added += 1
            except Exception:
                pass

        if added > 0:
            mk.Build()
            if mk.IsDone():
                return _transform_solid_with_trsf(cq.Solid(mk.Shape()), face_trsf)
    except Exception:
        pass
    return solid


def _apply_min_top_thickness(cav_scaled: cq.Solid,
                             kc: KeycapConfig,
                             n: int,
                             face_offset: Tuple[float, float, float]) -> cq.Solid:


    try:
        ai = compute_angle_index(n)
        top_z_rel = max(0.0, adjust_offsets(n, face_offset, ai)[2])
        nominal_top_thickness = top_z_rel * (1.0 - kc.cavity)
        extra_drop = max(0.0, kc.top_thickness_min - nominal_top_thickness)
        if extra_drop > 1e-6:
            return translate_solid(cav_scaled, 0.0, 0.0, -extra_drop)
    except Exception:
        pass
    return cav_scaled


def _stem_post_single(sc: StemConfig, height: float,
                      lift: float, x_off: float = 0.0) -> cq.Workplane:


    d = sc.wing_breadth + sc.wing_thickness
    r = d / 2.0

    post = (cq.Workplane("XY")
            .transformed(offset=(x_off, 0, lift))
            .circle(r).extrude(height))

    cross_h = (cq.Workplane("XY")
               .transformed(offset=(x_off, 0, lift))
               .rect(sc.wing_breadth, sc.wing_thickness).extrude(height))
    cross_v = (cq.Workplane("XY")
               .transformed(offset=(x_off, 0, lift))
               .rect(sc.wing_thickness, sc.wing_breadth).extrude(height))

    cone = (cq.Workplane("XY")
            .transformed(offset=(x_off, 0, lift))
            .circle(sc.wing_breadth / 2.0)
            .workplane(offset=0.5)
            .circle(sc.wing_thickness / 2.0)
            .loft())
    return post.cut(cross_h).cut(cross_v).cut(cone)


def make_stem_post(sc: StemConfig, height: float,
                   spacing: float = 0.0, lift: float = 0.0) -> cq.Workplane:

    if spacing == 0:
        return _stem_post_single(sc, height, lift)
    result = cq.Workplane("XY")
    for i in (-1, 0, 1):
        result = result.union(_stem_post_single(sc, height, lift, i * spacing))
    return result


def _root_base_geometry(sc: StemConfig, height: float, x_off: float = 0.0) -> cq.Workplane:

    scale_factor = 3 + height / (sc.wing_breadth + sc.wing_thickness)
    r_off = sc.wing_thickness * 2.0
    delta = -sc.wing_thickness
    eff = sc.wing_breadth + 2.0 * (r_off + delta)
    if eff < 0.5:
        eff = 0.5
    return (cq.Workplane("XY")
            .transformed(offset=(x_off, 0, 0))
            .rect(eff, eff)
            .workplane(offset=height)
            .rect(eff * scale_factor, eff * scale_factor)
            .loft())


def _root_transition(sc: StemConfig, x_off: float = 0.0) -> cq.Workplane:

    d = sc.wing_breadth + sc.wing_thickness
    return (cq.Workplane("XY")
            .transformed(offset=(x_off, 0, -sc.wing_thickness))
            .circle(d / 2.0)
            .workplane(offset=sc.wing_thickness * 2)
            .circle(d / 2.0 * 1.325)
            .loft())


def _vent_slot(sc: StemConfig, x_off: float, y_off: float,
               height: float) -> cq.Workplane:

    return (cq.Workplane("XY")
            .transformed(offset=(x_off, y_off, 0))
            .slot2D(sc.wing_thickness * 4, sc.wing_thickness * 2, 0)
            .extrude(height))


def make_root_geometry(sc: StemConfig, height: float,
                       spacing: float = 0.0) -> cq.Workplane:

    if height < 0.1:
        return cq.Workplane("XY")

    d = sc.wing_breadth + sc.wing_thickness
    t = sc.wing_thickness
    vent_y = sc.wing_breadth + sc.wing_thickness

    if spacing == 0:
        well = _root_base_geometry(sc, height)
        well_shift = _root_base_geometry(sc, height).translate((0, 0, t))
        cyl = cq.Workplane("XY").circle(d / 2.0).extrude(t)
        result = well.cut(well_shift).cut(cyl)
        try:
            result = result.union(_root_transition(sc))
        except Exception:
            pass

        for j in (-1, 1):
            try:
                result = result.cut(_vent_slot(sc, 0, vent_y * j, height))
            except Exception:
                pass
        return result
    else:

        wells = cq.Workplane("XY")
        for i in (-1, 1):
            wells = wells.union(_root_base_geometry(sc, height, spacing * i))
        wells_shift = cq.Workplane("XY")
        for i in (-1, 1):
            bg = _root_base_geometry(sc, height, spacing * i).translate((0, 0, t))
            wells_shift = wells_shift.union(bg)
        cyls = cq.Workplane("XY")
        for i in (-1, 0, 1):
            c = (cq.Workplane("XY")
                 .transformed(offset=(spacing * i, 0, 0))
                 .circle(d / 2.0).extrude(t))
            cyls = cyls.union(c)
        result = wells.cut(wells_shift).cut(cyls)
        for i in (-1, 0, 1):
            try:
                result = result.union(_root_transition(sc, spacing * i))
            except Exception:
                pass

        for i in (-1, 0, 1):
            for j in (-1, 1):
                try:
                    result = result.cut(_vent_slot(sc, spacing * i, vent_y * j, height))
                except Exception:
                    pass
        return result


def make_root_geometry_solid(sc: StemConfig, height: float,
                             spacing: float = 0.0) -> cq.Workplane:


    if height < 0.1:
        return cq.Workplane("XY")

    if spacing == 0:
        result = _root_base_geometry(sc, height)
        try:
            result = result.union(_root_transition(sc))
        except Exception:
            pass
        return result
    else:
        result = cq.Workplane("XY")
        for i in (-1, 1):
            result = result.union(_root_base_geometry(sc, height, spacing * i))
        for i in (-1, 0, 1):
            try:
                result = result.union(_root_transition(sc, spacing * i))
            except Exception:
                pass
        return result



def _fillet_stem_entry_rim(wp: cq.Workplane,
                              sc: StemConfig,
                              lift: float = 0.0,
                              radius: float = STEM_ENTRY_FILLET_RADIUS) -> cq.Workplane:
    """
    Round ONLY the OUTER circular rim at the free/open end of the MX stem socket.

    This is the rim visible around the cross-shaped opening and the end pushed
    onto the switch stem.  The internal cross geometry is not selected.

    Geometry limit:
      outer radius = (4.1 + 1.17) / 2 = 2.635 mm
      cross half-width = 4.1 / 2 = 2.050 mm
      minimum radial wall = 0.585 mm

    Therefore a true 1.0 mm edge fillet cannot fit without intersecting the
    internal cross cavity.  0.50 mm is used as the practical maximum here.
    """
    if radius <= 0.0:
        return wp

    stem_outer_d = sc.wing_breadth + sc.wing_thickness
    tol_z = 0.08
    tol_d = 0.20
    result_solids = []

    for solid in wp.solids().vals():
        target_edges = []

        for edge in solid.Edges():
            bb = edge.BoundingBox()

            # The desired outer rim lies in the entry plane z = lift.
            if abs(bb.zmin - lift) > tol_z or abs(bb.zmax - lift) > tol_z:
                continue

            sx = bb.xmax - bb.xmin
            sy = bb.ymax - bb.ymin

            # Only the full circular outside edge spans the complete diameter
            # in both X and Y. The cross-opening edges are much smaller.
            if abs(sx - stem_outer_d) <= tol_d and abs(sy - stem_outer_d) <= tol_d:
                target_edges.append(edge)

        if not target_edges:
            print("[stem entry fillet] WARNING: outer entry rim was not found; stem left unchanged")
            result_solids.append(solid)
            continue

        mk = BRepFilletAPI_MakeFillet(solid.wrapped)
        for edge in target_edges:
            mk.Add(radius, edge.wrapped)

        mk.Build()
        if not mk.IsDone():
            print(
                f"[stem entry fillet] WARNING: {radius:.3f} mm fillet failed; "
                "stem left unchanged. Reduce STEM_ENTRY_FILLET_RADIUS."
            )
            result_solids.append(solid)
            continue

        result_solids.append(cq.Solid(mk.Shape()))

    out = cq.Workplane("XY")
    for s in result_solids:
        out = out.add(s)
    return out


@_trace("make_stem")
def make_stem(sc: StemConfig, height: float,
              spacing: float = 0.0, lift: float = 0.0) -> cq.Workplane:


    stem_h = min(height - lift, 4.0)
    if stem_h < 0.1:
        return cq.Workplane("XY")
    post = make_stem_post(sc, stem_h, spacing, lift)
    result = post

    ext_h = height - lift - stem_h
    if ext_h > 0.1:
        d = sc.wing_breadth + sc.wing_thickness
        r = d / 2.0
        if spacing == 0:
            ext = (cq.Workplane("XY")
                   .transformed(offset=(0, 0, lift + stem_h))
                   .circle(r).extrude(ext_h))
        else:
            ext = cq.Workplane("XY")
            for i in (-1, 0, 1):
                cyl = (cq.Workplane("XY")
                       .transformed(offset=(i * spacing, 0, lift + stem_h))
                       .circle(r).extrude(ext_h))
                ext = ext.union(cyl)
        try:
            result = result.union(ext)
        except Exception:
            pass


    if STEM_ENTRY_FILLET_RADIUS > 0.0:
        result = _fillet_stem_entry_rim(
            result,
            sc,
            lift=lift,
            radius=STEM_ENTRY_FILLET_RADIUS,
        )

    return result


@_trace("make_stem_boot")
def make_stem_boot(sc: StemConfig, lift: float,
                   support_top_thin: float = 0.8,
                   extra_depth: float = 0.0) -> Optional[cq.Workplane]:


    if lift <= 0:
        return None
    t = sc.wing_thickness
    stem_d = sc.wing_breadth + sc.wing_thickness
    stem_r = stem_d / 2.0
    foot_r = stem_r + t
    foot_h = min(t, lift * 0.1)


    foot = (cq.Workplane("XY")
            .circle(foot_r).circle(max(foot_r - t, 0.5))
            .extrude(foot_h))


    n_seg = 4
    tine_h = lift * 0.9
    bar_t = max(t * 0.4, 0.3)
    slot_t = math.pi * stem_r / n_seg
    inner_r = max(stem_r - bar_t, sc.wing_breadth / 2.0)

    tines = (cq.Workplane("XY")
             .circle(stem_r).circle(inner_r)
             .extrude(tine_h))

    for i in range(n_seg):
        a = i * 360.0 / n_seg + 360.0 / (n_seg * 2)
        slot = (cq.Workplane("XY")
                .box(slot_t, stem_d * 2, tine_h, centered=(True, True, False)))
        slot = slot.rotate((0, 0, 0), (0, 0, 1), a)
        tines = tines.cut(slot)


    ubt = bar_t * support_top_thin
    uth = lift * 0.1
    inner_r_u = max(stem_r - ubt, sc.wing_breadth / 2.0)
    upper_tines = (cq.Workplane("XY")
                   .transformed(offset=(0, 0, tine_h))
                   .circle(stem_r).circle(inner_r_u)
                   .extrude(uth))
    for i in range(n_seg):
        a = i * 360.0 / n_seg + 360.0 / (n_seg * 2)
        slot = (cq.Workplane("XY")
                .transformed(offset=(0, 0, tine_h))
                .box(slot_t, stem_d * 2, uth, centered=(True, True, False)))
        slot = slot.rotate((0, 0, 0), (0, 0, 1), a)
        upper_tines = upper_tines.cut(slot)

    try:
        result = foot.union(tines).union(upper_tines)
    except Exception:
        result = foot


    if extra_depth > 0.1:
        try:
            tines_ext = (cq.Workplane("XY")
                         .transformed(offset=(0, 0, -extra_depth))
                         .circle(stem_r).circle(inner_r)
                         .extrude(extra_depth))
            for i in range(n_seg):
                a = i * 360.0 / n_seg + 360.0 / (n_seg * 2)
                slot_e = (cq.Workplane("XY")
                          .transformed(offset=(0, 0, -extra_depth))
                          .box(slot_t, stem_d * 2, extra_depth,
                               centered=(True, True, False)))
                slot_e = slot_e.rotate((0, 0, 0), (0, 0, 1), a)
                tines_ext = tines_ext.cut(slot_e)
            result = result.union(tines_ext)
        except Exception:
            pass

    return result


@_trace("make_keycap_boot")
def make_keycap_boot(kc: KeycapConfig, unit: float = 1.0,
                     lift: float = 2.0, support_top_thin: float = 0.8) -> Optional[cq.Solid]:


    if lift <= 0:
        return None

    w = kc.base_width
    r = kc.base_r
    cav = kc.cavity
    foot_h = lift * 0.125
    tine_size = w * 0.1
    sx, sy = w * unit, w
    tw, th = sx + 2.0 * r, sy + 2.0 * r
    cr = min(r, tw / 2.0 - 0.01, th / 2.0 - 0.01)
    if cr < 0.001:
        cr = 0.001


    with _trace_block("make_keycap_boot.foot_outer"):
        outer = (cq.Workplane("XY").sketch()
                 .rect(tw, th).vertices().fillet(cr)
                 .finalize().extrude(foot_h))
    inset = r * 4.0
    iw, ih = tw - 2.0 * inset, th - 2.0 * inset
    if iw > 0.1 and ih > 0.1:
        icr = min(cr, iw / 2.0 - 0.01, ih / 2.0 - 0.01)
        if icr < 0.001:
            icr = 0.001
        with _trace_block("make_keycap_boot.foot_inner"):
            inner = (cq.Workplane("XY").sketch()
                     .rect(iw, ih).vertices().fillet(icr)
                     .finalize().extrude(foot_h))
        try:
            with _trace_block("make_keycap_boot.foot_cut"):
                foot = outer.cut(inner)
        except Exception:
            foot = outer
    else:
        foot = outer


    gap    = 0.075
    uth    = (lift - lift * 0.88) * 2.0
    tine_h = lift - uth

    fin_w   = max(w * 0.038, 0.22)
    u_fin_w = max(fin_w * 0.5, 0.12)
    n_fins  = 5

    hx = tw / 2.0
    hy = th / 2.0


    clip_ow  = tw - 2.0 * gap
    clip_oh  = th - 2.0 * gap
    clip_ocr = min(cr, clip_ow / 2.0 - 0.001, clip_oh / 2.0 - 0.001)
    if clip_ocr < 0.001:
        clip_ocr = 0.001


    inner_w  = sx * cav + 2.0 * r * cav + 2.0 * gap
    inner_h  = sy * cav + 2.0 * r * cav + 2.0 * gap
    icr      = min(cr * cav, inner_w / 2.0 - 0.001, inner_h / 2.0 - 0.001)
    if icr < 0.001:
        icr = 0.001

    with _trace_block("make_keycap_boot.clip_prep"):
        clip_outer_h = (cq.Workplane("XY").sketch()
                        .rect(clip_ow, clip_oh).vertices().fillet(clip_ocr)
                        .finalize().extrude(tine_h))
        clip_inner_h = (cq.Workplane("XY").sketch()
                        .rect(inner_w, inner_h).vertices().fillet(icr)
                        .finalize().extrude(tine_h))
        clip_outer_u = (cq.Workplane("XY").sketch()
                        .rect(clip_ow, clip_oh).vertices().fillet(clip_ocr)
                        .finalize().extrude(lift))
        clip_inner_u = (cq.Workplane("XY").sketch()
                        .rect(inner_w, inner_h).vertices().fillet(icr)
                        .finalize().extrude(lift))

    def _clip_group(blk, is_upper=False):
        co = clip_outer_u if is_upper else clip_outer_h
        ci = clip_inner_u if is_upper else clip_inner_h
        try:
            blk = blk.intersect(co)
        except Exception:
            pass
        try:
            blk = blk.cut(ci)
        except Exception:
            pass
        return blk

    lower_side_fins = cq.Workplane("XY")
    lower_corner_fins = cq.Workplane("XY")
    upper_side_fins = cq.Workplane("XY")
    upper_corner_fins = cq.Workplane("XY")

    corner_diag = max(w * 0.07, 0.50)
    avail_x = clip_ow - 2.0 * corner_diag
    avail_y = clip_oh - 2.0 * corner_diag
    step_x  = avail_x / (n_fins + 1)
    step_y  = avail_y / (n_fins + 1)

    fin_depth_y = clip_oh * 0.20
    fin_depth_x = clip_ow * 0.20


    with _trace_block("make_keycap_boot.lower_side_fins"):
        for side in ('+Y', '-Y', '+X', '-X'):
            for i in range(n_fins):
                if side in ('+Y', '-Y'):
                    xpos   = -avail_x / 2.0 + step_x * (i + 1)
                    yedge  = (hy - gap) if side == '+Y' else -(hy - gap)
                    fy_ctr = yedge - (fin_depth_y / 2.0) * (1.0 if yedge > 0 else -1.0)
                    blk = (cq.Workplane("XY")
                           .box(fin_w, fin_depth_y, tine_h, centered=(True, True, False))
                           .translate((xpos, fy_ctr, 0)))
                else:
                    ypos   = -avail_y / 2.0 + step_y * (i + 1)
                    xedge  = (hx - gap) if side == '+X' else -(hx - gap)
                    fx_ctr = xedge - (fin_depth_x / 2.0) * (1.0 if xedge > 0 else -1.0)
                    blk = (cq.Workplane("XY")
                           .box(fin_depth_x, fin_w, tine_h, centered=(True, True, False))
                           .translate((fx_ctr, ypos, 0)))
                lower_side_fins = lower_side_fins.union(blk)
        lower_side_fins = _clip_group(lower_side_fins)


    corner_fin_len = corner_diag * 1.35
    with _trace_block("make_keycap_boot.lower_corner_fins"):
        for sx_s in (-1.0, 1.0):
            for sy_s in (-1.0, 1.0):
                cx  = sx_s * (clip_ow / 2.0 - corner_diag * 0.5)
                cy  = sy_s * (clip_oh / 2.0 - corner_diag * 0.5)

                ang = 45.0 if sx_s * sy_s > 0 else -45.0
                blk = (cq.Workplane("XY")
                       .box(corner_fin_len, fin_w, tine_h, centered=(True, True, False))
                       .translate((cx, cy, 0))
                       .rotate((cx, cy, 0), (cx, cy, 1), ang))
                lower_corner_fins = lower_corner_fins.union(blk)
        lower_corner_fins = _clip_group(lower_corner_fins)


    with _trace_block("make_keycap_boot.upper_side_fins"):
        for side in ('+Y', '-Y', '+X', '-X'):
            for i in range(n_fins):
                if side in ('+Y', '-Y'):
                    xpos   = -avail_x / 2.0 + step_x * (i + 1)
                    yedge  = (hy - gap) if side == '+Y' else -(hy - gap)
                    fy_ctr = yedge - (fin_depth_y * 0.85 / 2.0) * (1.0 if yedge > 0 else -1.0)
                    ublk = (cq.Workplane("XY")
                            .box(u_fin_w, fin_depth_y * 0.85, uth,
                                 centered=(True, True, False))
                            .translate((xpos, fy_ctr, tine_h)))
                else:
                    ypos   = -avail_y / 2.0 + step_y * (i + 1)
                    xedge  = (hx - gap) if side == '+X' else -(hx - gap)
                    fx_ctr = xedge - (fin_depth_x * 0.85 / 2.0) * (1.0 if xedge > 0 else -1.0)
                    ublk = (cq.Workplane("XY")
                            .box(fin_depth_x * 0.85, u_fin_w, uth,
                                 centered=(True, True, False))
                            .translate((fx_ctr, ypos, tine_h)))
                upper_side_fins = upper_side_fins.union(ublk)
        upper_side_fins = _clip_group(upper_side_fins, is_upper=True)


    with _trace_block("make_keycap_boot.upper_corner_fins"):
        for sx_s in (-1.0, 1.0):
            for sy_s in (-1.0, 1.0):
                cx  = sx_s * (clip_ow / 2.0 - corner_diag * 0.5)
                cy  = sy_s * (clip_oh / 2.0 - corner_diag * 0.5)
                ang = 45.0 if sx_s * sy_s > 0 else -45.0
                ublk = (cq.Workplane("XY")
                        .box(corner_fin_len * 0.85, u_fin_w, uth,
                             centered=(True, True, False))
                        .translate((cx, cy, tine_h))
                        .rotate((cx, cy, tine_h), (cx, cy, tine_h + 1), ang))
                upper_corner_fins = upper_corner_fins.union(ublk)
        upper_corner_fins = _clip_group(upper_corner_fins, is_upper=True)

    try:
        with _trace_block("make_keycap_boot.foot_tines_union"):
            tines = cq.Workplane("XY")
            tines = tines.union(lower_side_fins)
            tines = tines.union(lower_corner_fins)
            tines = tines.union(upper_side_fins)
            tines = tines.union(upper_corner_fins)
            result = foot.union(tines)
    except Exception:
        result = foot


    _w_offset = 1.5
    _t_offset = 3.5
    _net = _w_offset - _t_offset
    boot_cut_w = tw + 2.0 * _net
    boot_cut_h = th + 2.0 * _net
    if boot_cut_w > 1.0 and boot_cut_h > 1.0:
        _bcr = min(cr, boot_cut_w / 2.0 - 0.01, boot_cut_h / 2.0 - 0.01)
        if _bcr < 0.001:
            _bcr = 0.001
        with _trace_block("make_keycap_boot.boot_cut_shape"):
            boot_cut = (cq.Workplane("XY").sketch()
                        .rect(boot_cut_w, boot_cut_h).vertices().fillet(_bcr)
                        .finalize().extrude(lift))
        try:
            with _trace_block("make_keycap_boot.boot_cut_apply"):
                result = result.cut(boot_cut)
        except Exception:
            pass

    solids = result.solids().vals()
    return solids[0] if solids else None


def make_legend(symbol: str, lg: LegendConfig = LG) -> Optional[cq.Workplane]:


    if not symbol or lg.depth == 0:
        return None
    actual = len(symbol) * lg.base_width
    eff = min(lg.fit_width, actual)
    sr = eff / lg.depth if lg.depth != 0 else 1.0
    sf = lg.fit_width / actual if actual > lg.fit_width else 1.0
    try:
        txt = cq.Workplane("XY").text(
            symbol, lg.base_width * sf, -abs(lg.depth),
            halign="center", valign="center", font=lg.font)
        limiter = cq.Workplane("XY").sphere(abs(lg.depth) * sr)
        try:
            return txt.intersect(limiter)
        except Exception:
            return txt
    except Exception:
        return None


def _make_inner_label_solid(symbol: str, kb_h: float,
                            cav_scaled: Optional[cq.Solid] = None,
                            kc: 'KeycapConfig' = None,
                            n: int = 30,
                            face_offset: Tuple[float,float,float] = (0,0,7),
                            face_angle: Tuple[float,float,float] = (0,0,0)) -> List[cq.Solid]:


    try:
        font_size   = 3.0
        relief_mm   = 0.8
        extrude_h   = 3.0
        bold_symbol_fonts = {
            "\\": ("DejaVu Sans:style=Bold", 1.00),
            ":": ("DejaVu Sans:style=Bold", 1.00),
            '"': ("DejaVu Sans:style=Bold", 1.00),
            "[": ("DejaVu Sans:style=Bold", 1.03),
            "]": ("DejaVu Sans:style=Bold", 1.03),
        }


        if cav_scaled is not None:
            cav_bb   = cav_scaled.BoundingBox()
            cav_zmin = cav_bb.zmin
            cav_zmax = cav_bb.zmax
        else:
            cav_zmin = kb_h
            cav_zmax = kb_h + face_offset[2]

        cav_h = max(cav_zmax - cav_zmin, 0.5)


        fixed_offset = 3.0
        z_label = cav_zmin + min(fixed_offset, cav_h * 0.45)
        margin  = max(0.4, cav_h * 0.08)
        z_label = max(cav_zmin + margin, min(cav_zmax - margin, z_label))


        cav_ymax = None
        if cav_scaled is not None:
            z_c = max(cav_zmin + 0.2, min(cav_zmax - 0.2, z_label))
            try:
                slab = (cq.Workplane("XY")
                        .box(20, 100, 2.0, centered=(True, True, False))
                        .translate((0, 0, z_c - 1.0)))
                ci = (cq.Workplane("XY").add(cav_scaled)
                      .intersect(slab).solids().vals())
                if ci:
                    cav_ymax = ci[0].BoundingBox().ymax
            except Exception:
                pass
        if cav_ymax is None:
            if cav_scaled is not None:
                cav_ymax = cav_scaled.BoundingBox().ymax
            else:
                cav_ymax = 7.0


        pitch_angle = abs(face_angle[0])
        if kc is not None:
            base_y = (kc.base_width / 2.0 + kc.base_r) * kc.cavity
            face_y = (kc.face_width / 2.0 + kc.face_r) * kc.cavity
            slope  = (face_y - base_y) / cav_h
            wall_angle = max(3.0, min(abs(math.degrees(math.atan(slope))) + pitch_angle * 0.6, 65.0))
        else:
            wall_angle = 10.0


        symbol_font, font_scale = bold_symbol_fonts.get(symbol, ("Arial", 1.0))
        eff_font = max(min(font_size, cav_h * 0.55), 1.2) * font_scale

        try:
            txt = (cq.Workplane("XZ")
                   .text(symbol, eff_font, extrude_h,
                         halign="center", valign="center",
                         font=symbol_font))
        except Exception:
            txt = (cq.Workplane("XZ")
                   .text(symbol, eff_font, extrude_h,
                         halign="center", valign="center",
                         font="Arial"))


        t_mirror = gp_GTrsf()
        t_mirror.SetVectorialPart(gp_Mat(1, 0, 0, 0, -1, 0, 0, 0, 1))
        mirrored: List[cq.Solid] = []
        for s in txt.solids().vals():
            mirrored.append(
                cq.Solid(BRepBuilderAPI_GTransform(s.wrapped, t_mirror, True).Shape()))
        if not mirrored:
            return []


        target_ymin = cav_ymax - relief_mm

        placed = []
        for s in mirrored:
            s_rot    = rotate_solid(s, wall_angle, 0.0, 0.0)
            s_placed = translate_solid(s_rot, 0.0, 0.0, z_label)
            placed.append(s_placed)


        common_ymin = min(s.BoundingBox().ymin for s in placed) if placed else target_ymin
        dy     = target_ymin - common_ymin
        result = [translate_solid(s, 0.0, dy, 0.0) for s in placed]
        return result

    except Exception:
        return []


def _make_homing_bump(kc: KeycapConfig, n: int,
                      face_offset: Tuple[float, float, float],
                      face_angle: Tuple[float, float, float],
                      z_base: float,
                      bump_w: float = 3.0,
                      bump_h: float = 0.5,
                      bump_depth: float = 0.16,
                      bump_y_offset: float = -2.0,
                      bump_fillet: float = 0.15,
                      dimple_depth: float = 0.0,
                      bump_embed: float = 0.05,
                      face_tilt: float = 0.0) -> Optional[cq.Solid]:


    try:

        ai = compute_angle_index(n)
        off = adjust_offsets(n, face_offset, ai)
        ang = adjust_angles(n, face_angle, ai)
        if abs(face_tilt) > 1e-6:
            ang = (ang[0] + face_tilt, ang[1], ang[2])
        top_z = off[2] + z_base
        top_x = off[0]
        top_y = off[1]


        local_drop = 0.0
        if dimple_depth > 0:
            dimple_size = (kc.face_width + kc.face_r * 2.0) * 1.125
            sphere_d = dimple_size - kc.dimple_inset * 2.0
            sphere_r = sphere_d / 2.0
            if sphere_r > 0.1 and dimple_size > 0.01:
                z_sc = dimple_depth / (dimple_size * 0.5)
                z_tr = dimple_size * 0.5 * (dimple_depth / dimple_size)
                semi_c = sphere_r * abs(z_sc)
                rr = bump_y_offset * bump_y_offset
                if semi_c > 1e-6 and rr < sphere_r * sphere_r:
                    z_lower = z_tr - semi_c * math.sqrt(max(0.0, 1.0 - rr / (sphere_r * sphere_r)))
                    local_drop = max(0.0, -z_lower)


        r = min(bump_fillet, bump_w / 2.0 - 0.01, bump_h / 2.0 - 0.01)
        if r < 0.01:
            r = 0.01
        bump = (cq.Workplane("XY")
                .sketch().rect(bump_w, bump_h).vertices().fillet(r)
                .finalize().extrude(bump_depth))

        bump_solid = bump.val()
        bump_solid = translate_solid(
            bump_solid,
            0.0,
            bump_y_offset,
            -(local_drop + bump_embed if dimple_depth > 0 else bump_embed)
        )


        trsf = _compose_trsf(ang[0], ang[1], ang[2], top_x, top_y, top_z)
        return cq.Solid(BRepBuilderAPI_Transform(bump_solid.wrapped, trsf, True).Shape())
    except Exception:
        return None


def _engrave_top_legend(
    body: cq.Solid,
    symbol: str,
    kc: KeycapConfig,
    n: int,
    face_offset: Tuple[float, float, float],
    face_angle: Tuple[float, float, float],
    kb_h: float,
    dimple_depth: float,
    face_tilt: float,
) -> cq.Solid:
    """
    Engrave a centered legend into the actual concave top surface.

    The cutter starts at the nominal top plane and reaches through the dish
    only far enough to enter the real surface by TOP_LEGEND_DEPTH.
    This keeps the complete glyph visible while avoiding the previous
    excessive cutter depth that could turn closed letters into through-holes.
    """
    if not TOP_LEGENDS or not symbol:
        return body

    try:
        # Need to traverse the dish depth before reaching the center surface.
        # Only a tiny boolean overlap is added beyond the requested engraving.
        cutter_depth = max(
            0.15,
            abs(dimple_depth) + TOP_LEGEND_DEPTH + 0.05
        )

        txt_wp = cq.Workplane("XY").text(
            symbol,
            TOP_LEGEND_SIZE,
            -cutter_depth,
            halign="center",
            valign="center",
            font=TOP_LEGEND_FONT,
        )
        txt_solids = txt_wp.solids().vals()
        if not txt_solids:
            return body

        ai = compute_angle_index(n)
        off = adjust_offsets(n, face_offset, ai)
        ang = adjust_angles(n, face_angle, ai)
        if abs(face_tilt) > 1e-6:
            ang = (ang[0] + face_tilt, ang[1], ang[2])

        # Start just above the nominal top surface.
        top_origin = (
            off[0],
            off[1],
            off[2] + kb_h + 0.03
        )

        trsf = _compose_trsf(
            ang[0], ang[1], ang[2],
            top_origin[0], top_origin[1], top_origin[2]
        )

        cutters = [
            cq.Solid(BRepBuilderAPI_Transform(s.wrapped, trsf, True).Shape())
            for s in txt_solids
        ]
        tool = cutters[0] if len(cutters) == 1 else cq.Compound.makeCompound(cutters)

        cut_wp = (
            cq.Workplane("XY")
            .add(body)
            .cut(cq.Workplane("XY").add(tool))
        )
        out = cut_wp.solids().vals()
        return out[0] if out else body
    except Exception as e:
        print(f"[top legend] {symbol!r} engraving failed: {e}")
        return body



def _fuse_and_fillet_stem_cap_root(body: cq.Solid,
                                    stem_solid: cq.Solid,
                                    sc: StemConfig,
                                    radius: float = STEM_CAP_ROOT_RADIUS) -> cq.Solid:
    """
    Fuse stem + keycap body and fillet the REAL circular/oval intersection edge
    where the outside of the stem meets the inner keycap surface.

    Adaptive behavior:
      - first tries STEM_CAP_ROOT_RADIUS
      - if that fails, reduces by STEM_CAP_ROOT_RADIUS_STEP
      - stops at STEM_CAP_ROOT_RADIUS_MIN
      - if nothing succeeds, leaves the stem sharp

    No artificial collar is created. The fillet follows the actual junction
    between the stem OD and the sloped/curved inner cap surface.
    """
    fused_parts = (
        cq.Workplane("XY")
        .add(body)
        .union(cq.Workplane("XY").add(stem_solid))
        .solids()
        .vals()
    )
    if not fused_parts:
        print("[stem cap root fillet] WARNING: body/stem fuse failed")
        return body

    fused = fused_parts[0]

    if radius <= 0.0:
        return fused

    stem_d = sc.wing_breadth + sc.wing_thickness
    candidates = []

    # Find the actual cap-side stem/root junction edge.
    # It is centered on the stem axis, spans about the stem OD in X/Y,
    # and is non-planar in Z when the inner cap surface is tilted.
    for edge in fused.Edges():
        bb = edge.BoundingBox()
        sx = bb.xmax - bb.xmin
        sy = bb.ymax - bb.ymin
        sz = bb.zmax - bb.zmin
        cx = (bb.xmax + bb.xmin) * 0.5
        cy = (bb.ymax + bb.ymin) * 0.5

        if abs(cx) > 0.5 or abs(cy) > 0.5:
            continue
        if abs(sx - stem_d) > 0.35 or abs(sy - stem_d) > 0.35:
            continue
        if sz < 0.05:
            continue

        candidates.append(edge)

    if not candidates:
        print("[stem cap root fillet] WARNING: actual stem/cap root edge not found")
        return fused

    # Prefer the longest candidate: normally this is the full perimeter root edge.
    root_edge = max(candidates, key=lambda e: e.Length())

    preferred = max(float(radius), 0.0)
    minimum = max(float(STEM_CAP_ROOT_RADIUS_MIN), 0.0)
    step = max(float(STEM_CAP_ROOT_RADIUS_STEP), 0.01)

    # Clamp minimum so the loop always terminates sensibly.
    if minimum > preferred:
        minimum = preferred

    # Integer step count avoids cumulative floating-point drift.
    tries = int(math.floor((preferred - minimum) / step + 1e-9)) + 1
    radii = [preferred - i * step for i in range(tries)]

    # Ensure the exact minimum is tried if the step does not land on it.
    if not radii or radii[-1] > minimum + 1e-9:
        radii.append(minimum)

    for r_try in radii:
        r_try = max(r_try, minimum)

        try:
            mk = BRepFilletAPI_MakeFillet(fused.wrapped)
            mk.Add(r_try, root_edge.wrapped)
            mk.Build()

            if mk.IsDone():
                if r_try < preferred - 1e-6:
                    print(
                        f"[stem cap root fillet] reduced R{preferred:.2f} "
                        f"-> R{r_try:.2f}"
                    )
                return cq.Solid(mk.Shape())

        except Exception:
            pass

    print(
        f"[stem cap root fillet] WARNING: no radius from "
        f"R{preferred:.2f} down to R{minimum:.2f} succeeded; stem left sharp"
    )
    return fused




@_trace("build_keycap")
def build_keycap(
    kc: KeycapConfig = KC,
    sc: StemConfig = SC,
    face_offset: Tuple[float, float, float] = (0, 0, 5),
    face_angle: Tuple[float, float, float] = (0, 0, 0),
    dimple_depth: float = 1.2,
    n: int = 30,
    unit: float = 1.0,
    boot: Tuple[float, float] = (2.0, 3.2),
    face_tilt: float = 0.0,
    inner_label: str = "",
    top_legend: str = "",
    homing_bump: bool = False,
) -> List[cq.Solid]:


    kb_h, sb_h = boot
    if FDM_MODE:
        # The upstream boot values intentionally lift the printable geometry
        # so sacrificial support structures can be generated underneath.
        # For FDM, start both the cap shell and MX stem directly at Z=0.
        kb_h = 0.0
        sb_h = 0.0

    parts: List[cq.Solid] = []


    # Ergohaven's upstream generator includes sacrificial "boot"
    # structures intended to support the cap/stem during printing.
    # They are omitted in FDM_MODE; slicer-generated supports can be used instead.
    if not FDM_MODE:
        with _trace_block("build_keycap.stem_boot_build"):
            sb = make_stem_boot(sc, lift=sb_h, support_top_thin=kc.support_top_thin)
        if sb is not None:
            with _trace_block("build_keycap.stem_boot_unpack"):
                for s in sb.solids().vals():
                    parts.append(s)

        with _trace_block("build_keycap.keycap_boot_build"):
            kb = make_keycap_boot(kc, unit, kb_h, kc.support_top_thin)
        if kb is not None:
            parts.append(kb)


    with _trace_block("build_keycap.cavity_build_once"):
        cav_sol = build_cavity_solid(kc, n, face_offset, face_angle, unit, kb_h,
                                     dimple_depth=dimple_depth, face_tilt=face_tilt)


    # Upstream uses inner cavity labels such as A1/B1.
    # For these Keyball61 FDM caps we leave the inside clean and engrave
    # the actual key legend into the top surface instead.
    lbl_solid = []
    with _trace_block("build_keycap.body_build"):
        body = keycap_body(kc, n, face_offset, face_angle, unit, kb_h, dimple_depth,
                           face_tilt=face_tilt,
                           cavity_solid=cav_sol,
                           inner_label_solids=lbl_solid)

    if top_legend:
        with _trace_block("build_keycap.top_legend_engrave"):
            body = _engrave_top_legend(
                body, top_legend, kc, n, face_offset, face_angle,
                kb_h, dimple_depth, face_tilt
            )


    if homing_bump:
        with _trace_block("build_keycap.homing_bump_build"):
            hb = _make_homing_bump(kc, n, face_offset, face_angle, kb_h,
                                   dimple_depth=dimple_depth, face_tilt=face_tilt)
        if hb is not None:
            try:
                with _trace_block("build_keycap.homing_bump_union"):
                    body_wp = cq.Workplane("XY").add(body).union(cq.Workplane("XY").add(hb))
                    body_solids = body_wp.solids().vals()
                    if body_solids:
                        body = body_solids[0]
            except Exception:

                parts.append(hb)

    spacing = sc.base_spacing if unit >= 2.0 else 0.0
    stem_extra_h = face_offset[2] + kc.base_width
    with _trace_block("build_keycap.stem_build"):
        stem_wp = make_stem(sc, height=stem_extra_h, spacing=spacing, lift=sb_h)
    if cav_sol is not None:
        try:
            with _trace_block("build_keycap.stem_clip"):
                stem_clipped = (cq.Workplane("XY").add(stem_wp)
                                .intersect(cq.Workplane("XY").add(cav_sol)))
                for s in stem_clipped.solids().vals():
                    if STEM_CAP_ROOT_RADIUS > 0.0:
                        body = _fuse_and_fillet_stem_cap_root(
                            body,
                            s,
                            sc,
                            radius=STEM_CAP_ROOT_RADIUS,
                        )
                    else:
                        parts.append(s)
        except Exception:
            for s in stem_wp.solids().vals():
                parts.append(s)
    else:
        for s in stem_wp.solids().vals():
            parts.append(s)

    parts.append(body)


    # Lower wedge/tine/foot geometry is part of the upstream
    # sacrificial print-support system. Keep it for resin/upstream behavior,
    # omit it for FDM.
    if not FDM_MODE:
        th_w = kc.base_width + kc.base_r * 2.0
        tw_w = th_w * max(unit, 1.0)
        hx_w = tw_w / 2.0
        hy_w = th_w / 2.0

        pitch = face_angle[0]
        yaw   = face_angle[1]


        if abs(pitch) > 5.0:
            a_p = abs(pitch) + 10.0
            sp  = 1.0 if pitch > 0 else -1.0
        else:
            a_p = 25.0
            sp  = 1.0

        h_p = th_w * math.tan(math.radians(a_p))


        with _trace_block("build_keycap.wedge_core"):
            if sp > 0:
                wedge = (cq.Workplane("YZ")
                         .moveTo(hy_w, -h_p)
                         .lineTo(-hy_w, 0.0)
                         .lineTo(hy_w, 0.0)
                         .close()
                         .extrude(hx_w, both=True))
            else:
                wedge = (cq.Workplane("YZ")
                         .moveTo(-hy_w, -h_p)
                         .lineTo(hy_w, 0.0)
                         .lineTo(-hy_w, 0.0)
                         .close()
                         .extrude(hx_w, both=True))


        wedge_offset = 1.5
        _wcr = min(kc.base_r, tw_w / 2.0 - 0.01, th_w / 2.0 - 0.01)
        if _wcr < 0.001:
            _wcr = 0.001
        _wmh = max(tw_w, th_w)
        _tw_exp = tw_w + 2.0 * wedge_offset
        _th_exp = th_w + 2.0 * wedge_offset
        _wcr_exp = min(_wcr + wedge_offset * 0.5, _tw_exp / 2.0 - 0.01, _th_exp / 2.0 - 0.01)
        if _wcr_exp < 0.001:
            _wcr_exp = 0.001
        with _trace_block("build_keycap.wedge_clip_shape"):
            wedge_clip = (cq.Workplane("XY")
                          .transformed(offset=(0, 0, -_wmh))
                          .sketch().rect(_tw_exp, _th_exp).vertices().fillet(_wcr_exp)
                          .finalize().extrude(_wmh))


        wedge_unclipped = wedge
        with _trace_block("build_keycap.wedge_clip_apply"):
            try:
                wedge_for_stem = wedge_unclipped.intersect(wedge_clip)
            except Exception:
                wedge_for_stem = wedge_unclipped

            try:
                wedge = wedge.intersect(wedge_clip)
            except Exception:
                pass


        thin_offset = 3.5
        cut_w = _tw_exp - 2.0 * thin_offset
        cut_h = _th_exp - 2.0 * thin_offset
        _cut_cr = min(_wcr_exp, cut_w / 2.0 - 0.01, cut_h / 2.0 - 0.01)
        if _cut_cr < 0.001:
            _cut_cr = 0.001
        if cut_w > 1.0 and cut_h > 1.0:
            stem_cut = (cq.Workplane("XY")
                        .transformed(offset=(0, 0, -_wmh))
                        .sketch().rect(cut_w, cut_h).vertices().fillet(_cut_cr)
                        .finalize().extrude(_wmh * 2))
            try:
                with _trace_block("build_keycap.wedge_stem_cut"):
                    wedge = wedge.cut(stem_cut)
            except Exception:
                pass

        with _trace_block("build_keycap.wedge_unpack"):
            for s in wedge.solids().vals():
                parts.append(s)


        t_sb = sc.wing_thickness
        stem_d_sb = sc.wing_breadth + sc.wing_thickness
        stem_r_sb = stem_d_sb / 2.0
        bar_t_sb = max(t_sb * 0.4, 0.3)
        inner_r_ext = max(stem_r_sb - bar_t_sb, sc.wing_breadth / 2.0)

        ext_bottom = -(h_p + 0.5)
        ext_h = abs(ext_bottom)

        n_seg_ext = 4
        slot_t_ext = math.pi * stem_r_sb / n_seg_ext


        overlap = 0.5
        ext_h_full = ext_h + overlap

        def _build_one_tines_ext(ox: float) -> Optional[cq.Workplane]:
            te = (cq.Workplane("XY")
                  .transformed(offset=(ox, 0, ext_bottom))
                  .circle(stem_r_sb).circle(inner_r_ext)
                  .extrude(ext_h_full))
            for i in range(n_seg_ext):
                a = i * 360.0 / n_seg_ext + 360.0 / (n_seg_ext * 2)
                slot = (cq.Workplane("XY")
                        .transformed(offset=(ox, 0, ext_bottom))
                        .box(slot_t_ext, stem_d_sb * 2, ext_h_full,
                             centered=(True, True, False)))
                slot = slot.rotate((ox, 0, ext_bottom), (ox, 0, ext_bottom + 1), a)
                try:
                    te = te.cut(slot)
                except Exception:
                    pass
            return te

        if ext_h > 0.1:
            with _trace_block("build_keycap.tines_extension"):
                xs = [0.0] if spacing == 0 else [-spacing, 0.0, spacing]
                for ox in xs:
                    te = _build_one_tines_ext(ox)
                    if te is None:
                        continue


                    try:
                        clip_neg = (cq.Workplane("XY")
                                    .transformed(offset=(ox, 0, -200))
                                    .box(60, 60, 200, centered=(True, True, False)))
                        clip_pos = (cq.Workplane("XY")
                                    .transformed(offset=(ox, 0, 0))
                                    .box(60, 60, overlap + 0.01, centered=(True, True, False)))
                        te_lower = te.intersect(clip_neg).intersect(wedge_for_stem)
                        te_upper = te.intersect(clip_pos)
                        for wp in (te_lower, te_upper):
                            for s in wp.solids().vals():
                                parts.append(s)
                    except Exception:
                        for s in te.solids().vals():
                            parts.append(s)


        foot_r_sb_fe = stem_r_sb + t_sb
        foot_inner_r_fe = max(foot_r_sb_fe - t_sb, 0.5)
        foot_ext_h = abs(ext_bottom)

        if foot_ext_h > 0.1:
            with _trace_block("build_keycap.foot_extension"):
                if spacing == 0:
                    foot_ext = (cq.Workplane("XY")
                                .transformed(offset=(0, 0, ext_bottom))
                                .circle(foot_r_sb_fe).circle(foot_inner_r_fe)
                                .extrude(foot_ext_h))
                else:
                    foot_ext = cq.Workplane("XY")
                    for xi in (-1, 0, 1):
                        _f = (cq.Workplane("XY")
                              .transformed(offset=(xi * spacing, 0, ext_bottom))
                              .circle(foot_r_sb_fe).circle(foot_inner_r_fe)
                              .extrude(foot_ext_h))
                        foot_ext = foot_ext.union(_f)
                try:
                    foot_ext_clipped = foot_ext.intersect(wedge_for_stem)
                    for s in foot_ext_clipped.solids().vals():
                        parts.append(s)
                except Exception:
                    pass


    if FDM_MODE and FDM_LEVEL_TOP:
        parts = _fdm_level_top(parts, face_angle, face_tilt)

    return parts



def _fdm_level_top(solids, face_angle, face_tilt):
    rx = face_angle[0] + face_tilt
    ry = face_angle[1]

    # Level the top surface
    out = [rotate_solid(s, -rx, -ry, 0.0) for s in solids]

    # Optional: flip cap so the flat top face lies on the print bed
    if FDM_FLIP_TOP_DOWN:
        out = [rotate_solid(s, 180.0, 0.0, 0.0) for s in out]

    if not out:
        return out

    # Always place lowest geometry on Z=0
    min_z = min(s.BoundingBox().zmin for s in out)
    out = [translate_solid(s, 0.0, 0.0, -min_z) for s in out]

    return out



def build_keycap_compound(
    kc: KeycapConfig = KC, sc: StemConfig = SC,
    face_offset: Tuple[float, float, float] = (0, 0, 5),
    face_angle: Tuple[float, float, float] = (0, 0, 0),
    dimple_depth: float = 1.2, n: int = 30,
    unit: float = 1.0, boot: Tuple[float, float] = (2.0, 3.2),
    face_tilt: float = 0.0,
) -> cq.Compound:

    solids = build_keycap(kc, sc, face_offset, face_angle, dimple_depth,
                          n, unit, boot, face_tilt=face_tilt)
    return cq.Compound.makeCompound(solids)


def _reach_fn_row(i: int, h: float) -> Tuple[float, float, float]:
    return (3.75 - i * 1.5, -4.0, h)

def _angle_fn_row(i: int, a: Tuple[float, float]) -> Tuple[float, float, float]:
    return (-a[1] * 0.5, a[0] * 0.75, 0.0)

def _reach_matrix(i: int, j: int, h: float) -> Tuple[float, float, float]:
    return (3.75 - i * 1.5, -3.0 + j * 3.0, h)

def _angle_matrix(i: int, j: int, a: Tuple[float, float]) -> Tuple[float, float, float]:

    return (a[1], a[0], 0.0)


@_trace("_build_hand_solids")
def _build_hand_solids(
    design: list,
    lc: LayoutConfig,
    kc: KeycapConfig,
    sc: StemConfig,
    is_right: bool = False,
    include_fn: bool = False,
    key_angles: Optional[List[List[Tuple[float, float]]]] = None,
    key_height: Optional[List[List[Optional[float]]]] = None,
    key_face_tilt: Optional[List[List[float]]] = None,
    thumb_sweep: Optional[List[Tuple[float, float]]] = None,
    thumb_face_tilt: Optional[List[float]] = None,
) -> List[cq.Solid]:


    boot = (lc.boot_keycap, lc.boot_stem)
    all_solids: List[cq.Solid] = []
    n_cols = len(design)
    n_rows = len(design[0]) if n_cols > 0 else 0

    _key_angles = key_angles if key_angles is not None else [[(0.0, 0.0)] * n_cols for _ in range(n_rows)]
    _key_height = key_height if key_height is not None else [[None] * n_cols for _ in range(n_rows)]
    _key_face_tilt = key_face_tilt if key_face_tilt is not None else [[lc.face_tilt] * n_cols for _ in range(n_rows)]
    _thumb_sweep = thumb_sweep if thumb_sweep is not None else [(0.0, 0.0)] * 4
    _thumb_face_tilt = thumb_face_tilt if thumb_face_tilt is not None else [lc.face_tilt] * 4

    # Dedicated thumb clusters:
    # left = MO, Space, Backspace; right = Enter, MODown.
    # These use THUMB_SWEEP / THUMB_FACE_TILT. The only matrix exception is left Alt.
    _thumb_heights = THUMB_HEIGHTS_RIGHT if is_right else THUMB_HEIGHTS_LEFT

    if is_right:


        _key_height = [list(reversed(row)) for row in _key_height]
        _key_angles = [[(pitch, -yaw) for pitch, yaw in reversed(row)] for row in _key_angles]
        _key_face_tilt = [list(reversed(row)) for row in _key_face_tilt]
        _thumb_sweep = [(pitch, -yaw) for pitch, yaw in _thumb_sweep]


    # Top legends matching the user's CURRENT Keyball61 QMK keymap.
    #
    # Physical QMK rows:
    #   ESC  1 2 3 4 5        | 6 7 8 9 0 -
    #   `    Q W E R T        | Y U I O P =
    #   Ctrl A S D F G        | H J K L ; '
    #   Shift Z X C V B [     | ] N M , . / Shift
    #   GUI App Home End Alt Space Tab | Bspc Enter AltGr PgUp PgDn \ GUI
    #
    # Blank entries are matrix positions not generated by the current
    # personalized KEY_HEIGHT geometry.
    _TOP_LEGENDS_LEFT = [
        ["E",     "1",     "2",     "3",     "4",    "5",     ""],
        ["MM", "Q",     "W",     "E",     "R",    "T",     ""],
        ["S",   "A",     "S",     "D",     "F",    "G",     ""],
        ["C",    "Y",     "X",     "C",     "V",    "B",     ""],
        ["",        "[",     "]",     "",      "A",  "",      ""],
    ]

    _TOP_LEGENDS_RIGHT = [
        ["",        "6",     "7",     "8",     "9",    "0",     "BS"],
        ["",        "Z",     "U",     "I",     "O",    "P",     "Ü"],
        ["",        "H",     "J",     "K",     "L",    "Ö",     "Ä"],
        ["",        "N",     "M",     ",",     ".",    "-",     "$"],
        ["",        "",      "",      "",      "",     "AG",      ""],
    ]

    _TOP_LEGENDS_MATRIX = _TOP_LEGENDS_RIGHT if is_right else _TOP_LEGENDS_LEFT

    # Dedicated physical thumb clusters.
    # ONLY these caps use the thumb angles, except the left-row Alt override below.
    _THUMB_LEGENDS_LEFT = ["MU", "SP", "BS", ""]
    _THUMB_LEGENDS_RIGHT = ["ET", "MD", "", ""]
    _THUMB_LEGENDS = _THUMB_LEGENDS_RIGHT if is_right else _THUMB_LEGENDS_LEFT





    for i in range(n_cols):
        for j in range(n_rows):
            if PREVIEW_MODE == "thumbs":
                continue
            if PREVIEW_MODE == "row" and j != PREVIEW_ROW:
                continue
            if PREVIEW_MODE == "key":
                if PREVIEW_COL is None:
                    raise ValueError("PREVIEW_COL must be set when PREVIEW_MODE == 'key'")
                if j != PREVIEW_ROW or i != PREVIEW_COL:
                    continue

            _ang_data, height = design[i][j]

            _kh = _key_height[j][i] if (j < len(_key_height) and i < len(_key_height[j])) else None

            # Physical fifth row:
            # LEFT:  blank, [, ], blank, Alt
            # RIGHT: Enter + MODown are thumb caps, then trackball, then two
            #        far-right normal caps with no legends.
            if is_right and j == 4:
                _kh = 12.0 if i == 5 else (13.0 if i == 6 else 0.0)

            raw_h = _kh if _kh is not None else height
            if raw_h is None or raw_h <= 0:
                continue


            h = max(raw_h, lc.boot_keycap + 2.0)
            fo = (0.0, 0.0, h)

            _angles = _key_angles[j][i] if (j < len(_key_angles) and i < len(_key_angles[j])) else (0.0, 0.0)
            pitch, yaw = _angles
            fa = (pitch, yaw, 0.0)
            _face_tilt = (_key_face_tilt[j][i]
                          if j < len(_key_face_tilt) and i < len(_key_face_tilt[j])
                          else lc.face_tilt)

            # Special case requested for the physical left Alt key:
            # keep its matrix position, but give ONLY this key a thumb-like face angle.
            # Every other fifth-row key keeps the normal matrix angle.
            if (not is_right) and j == 4 and i == 4:
                _alt_tp, _alt_ty = _thumb_sweep[1]
                fa = (_alt_tp, _alt_ty, 0.0)
                _face_tilt = _thumb_face_tilt[1]

            _top_legend = (_TOP_LEGENDS_MATRIX[j][i]
                           if j < len(_TOP_LEGENDS_MATRIX) and i < len(_TOP_LEGENDS_MATRIX[j])
                           else "")

            if TOP_SURFACE_MODE == "flat":
                _dimple_depth = 0.0
            else:
                _dimple_depth = lc.dimple_depth

            _is_homing = HOMING_BUMP_ENABLED and (
                (not is_right and j == 2 and i == 4)
                or (is_right and j == 2 and i == 2)
            )
            parts = build_keycap(kc, sc, fo, fa, _dimple_depth, kc.slices, 1.0, boot,
                                 face_tilt=_face_tilt,
                                 inner_label="", top_legend=_top_legend,
                                 homing_bump=_is_homing)

            dx = i * lc.unit
            dy = j * -lc.unit
            for s in parts:
                all_solids.append(translate_solid(s, dx, dy, 0))


    # Thumbs are omitted in row/key preview modes for speed.
    if PREVIEW_MODE in ("row", "key"):
        return all_solids

    thumb_y = -lc.unit * n_rows
    if is_right:
        base_x = lc.unit
        step_x = lc.unit
    else:
        base_x = (n_cols - 2) * lc.unit
        step_x = -lc.unit

    for idx in range(4):
        tp, ty = _thumb_sweep[idx] if idx < len(_thumb_sweep) else (0.0, 0.0)
        _thumb_face = _thumb_face_tilt[idx] if idx < len(_thumb_face_tilt) else lc.face_tilt
        thumb_h = _thumb_heights[idx] if idx < len(_thumb_heights) else 0.0
        if thumb_h is None or thumb_h <= 0:
            continue
        fo = (0.0, 0.0, thumb_h)
        fa = (tp, ty, 0.0)

        _is_homing_thumb = HOMING_BUMP_ENABLED and (idx == 1)
        _thumb_legend = _THUMB_LEGENDS[idx] if idx < len(_THUMB_LEGENDS) else ""
        parts = build_keycap(kc, sc, fo, fa, 0.0, kc.slices, 1.0, boot,
                             face_tilt=_thumb_face,
                             inner_label="", top_legend=_thumb_legend,
                             homing_bump=_is_homing_thumb)
        dx = base_x + idx * step_x
        for s in parts:
            all_solids.append(translate_solid(s, dx, thumb_y, 0))


    if include_fn:
        for i in range(n_cols):
            _ang_data, height = design[i][0]
            _kh_fn = _key_height[0][i] if (len(_key_height) > 0 and i < len(_key_height[0])) else None
            h = _kh_fn if _kh_fn is not None else height
            if h is None or h <= 0:
                continue
            fo = (0.0, 0.0, h)
            _fn_angles = _key_angles[0][i] if (len(_key_angles) > 0 and i < len(_key_angles[0])) else (0.0, 0.0)
            fa = (_fn_angles[0], _fn_angles[1], 0.0)
            parts = build_keycap(kc, sc, fo, fa, lc.dimple_depth, kc.slices, 1.0, boot)
            fn_dy = lc.unit
            for s in parts:
                all_solids.append(translate_solid(s, i * lc.unit, fn_dy, 0))

    return all_solids


@_trace("build_layout")
def build_layout(
    sidemask: int = 3,
    include_fn: bool = False,
    kc: KeycapConfig = KC,
    sc: StemConfig = SC,
    lc: LayoutConfig = LC,
    key_angles: Optional[List[List[Tuple[float, float]]]] = None,
    key_height: Optional[List[List[Optional[float]]]] = None,
    key_face_tilt: Optional[List[List[float]]] = None,
    thumb_sweep: Optional[List[Tuple[float, float]]] = None,
    thumb_face_tilt: Optional[List[float]] = None,
) -> cq.Workplane:


    design = sweep_design(lc)
    all_solids: List[cq.Solid] = []

    if sidemask in (1, 3):
        left = _build_hand_solids(design, lc, kc, sc, False, include_fn,
                                  key_angles, key_height, key_face_tilt,
                                  thumb_sweep, thumb_face_tilt)
        dx = -lc.unit * 3.5 if sidemask == 1 else -lc.unit * 5.5
        all_solids.extend(translate_solid(s, dx, 0, 0) for s in left)

    if sidemask in (2, 3):
        right = _build_hand_solids(design, lc, kc, sc, True, include_fn,
                                   key_angles, key_height, key_face_tilt,
                                   thumb_sweep, thumb_face_tilt)
        dx = -lc.unit * 2.5 if sidemask == 2 else lc.unit * 0.5
        all_solids.extend(translate_solid(s, dx, 0, 0) for s in right)


    if all_solids:
        min_z = min(s.BoundingBox().zmin for s in all_solids)
        if min_z < -0.001:
            all_solids = [translate_solid(s, 0, 0, -min_z) for s in all_solids]
    return cq.Workplane("XY").newObject([cq.Compound.makeCompound(all_solids)])
    return cq.Workplane("XY")


def build_test_keycap(kc: KeycapConfig = KC, sc: StemConfig = SC,
                      lc: LayoutConfig = LC) -> cq.Workplane:

    solids = build_keycap(
        kc, sc,
        face_offset=(0, 0, lc.max_height),
        face_angle=(0, 0, 0),
        dimple_depth=lc.dimple_depth,
        n=kc.slices,
        unit=1.0,
        boot=(lc.boot_keycap, lc.boot_stem),
        face_tilt=lc.face_tilt,
    )
    min_z = min(s.BoundingBox().zmin for s in solids)
    if min_z < -0.001:
        solids = [translate_solid(s, 0, 0, -min_z) for s in solids]
    return cq.Workplane("XY").newObject([cq.Compound.makeCompound(solids)])


def export_step(wp: cq.Workplane, path: str) -> None:

    cq.exporters.export(wp, path)
    print(f"Exported: {path}")


def export_stl(wp: cq.Workplane, path: str) -> None:

    cq.exporters.export(wp, path, exportType="STL")
    print(f"Exported: {path}")


def _is_cq_editor() -> bool:

    try:
        show_object
        return True
    except NameError:
        pass

    try:
        from ocp_vscode import show
        return True
    except ImportError:
        return False


def _show(result: cq.Workplane, name: str = "ergohaven") -> None:

    try:
        show_object(result, name=name, options={"alpha": 0.0})
        return
    except NameError:
        pass
    try:
        from ocp_vscode import show
        show(result, names=[name])
    except Exception:
        pass


if _is_cq_editor():
    import traceback as _tb
    _preset = _QUALITY_PRESETS.get(QUALITY, _QUALITY_PRESETS["production"])
    _kc = KeycapConfig(slices=_preset["slices"])
    if PREVIEW_MODE == "key":
        print(f"[Ergohaven] MODE={MODE!r}, QUALITY={QUALITY!r} (slices={_kc.slices}), PREVIEW_MODE='key', ROW={PREVIEW_ROW}, COL={PREVIEW_COL}")
    elif PREVIEW_MODE == "row":
        print(f"[Ergohaven] MODE={MODE!r}, QUALITY={QUALITY!r} (slices={_kc.slices}), PREVIEW_MODE='row', ROW={PREVIEW_ROW}")
    elif PREVIEW_MODE == "thumbs":
        print(f"[Ergohaven] MODE={MODE!r}, QUALITY={QUALITY!r} (slices={_kc.slices}), PREVIEW_MODE='thumbs'")
    else:
        print(f"[Ergohaven] MODE={MODE!r}, QUALITY={QUALITY!r} (slices={_kc.slices}), PREVIEW_MODE='full'")
    try:
        if MODE == "single":
            _result = build_test_keycap(_kc)
            print(f"[Ergohaven] single keycap built OK")
            _show(_result, "test_keycap")
        elif MODE == "left":
            print("[Ergohaven] building left hand layout...")
            _result = build_layout(1, INCLUDE_FN_ROW, _kc, key_angles=KEY_ANGLES, key_height=KEY_HEIGHT, key_face_tilt=KEY_FACE_TILT, thumb_sweep=THUMB_SWEEP, thumb_face_tilt=THUMB_FACE_TILT)
            print(f"[Ergohaven] left hand built OK, solids: {len(_result.solids().vals())}")
            _show(_result, "left_hand")
        elif MODE == "right":
            print("[Ergohaven] building right hand layout...")
            _result = build_layout(2, INCLUDE_FN_ROW, _kc, key_angles=KEY_ANGLES, key_height=KEY_HEIGHT, key_face_tilt=KEY_FACE_TILT, thumb_sweep=THUMB_SWEEP, thumb_face_tilt=THUMB_FACE_TILT)
            print(f"[Ergohaven] right hand built OK, solids: {len(_result.solids().vals())}")
            _show(_result, "right_hand")
        elif MODE == "both":
            print("[Ergohaven] building both hands layout...")
            _result = build_layout(3, INCLUDE_FN_ROW, _kc, key_angles=KEY_ANGLES, key_height=KEY_HEIGHT, key_face_tilt=KEY_FACE_TILT, thumb_sweep=THUMB_SWEEP, thumb_face_tilt=THUMB_FACE_TILT)
            print(f"[Ergohaven] both hands built OK, solids: {len(_result.solids().vals())}")
            _show(_result, "ergohaven")
        else:
            print(f"[Ergohaven] Unknown MODE: {MODE!r}")
    except Exception as _e:
        print(f"[Ergohaven] ERROR: {_e}")
        _tb.print_exc()
    finally:
        _finalize_runtime_notes()

elif __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Ergohaven Keycaps v2 (CadQuery)")
    parser.add_argument("--mode", choices=["single", "left", "right", "both"],
                        default="single", help="Generation mode")
    parser.add_argument("--quality", choices=["draft", "production"],
                        default="production", help="Quality (draft=preview, production=export)")
    parser.add_argument("--fn-row", action="store_true", help="Include the F-row")
    parser.add_argument("--output", default=None, help="Output file (STEP/STL)")
    parser.add_argument("--slices", type=int, default=None,
                        help="Slice count override")
    args = parser.parse_args()

    preset = _QUALITY_PRESETS.get(args.quality, _QUALITY_PRESETS["production"])
    _slices = args.slices if args.slices is not None else preset["slices"]
    kc = KeycapConfig(slices=_slices)

    try:
        if args.mode == "single":
            result = build_test_keycap(kc)
            out = args.output or "test_keycap.step"
        elif args.mode == "left":
            result = build_layout(1, args.fn_row, kc, key_angles=KEY_ANGLES, key_height=KEY_HEIGHT, key_face_tilt=KEY_FACE_TILT, thumb_sweep=THUMB_SWEEP, thumb_face_tilt=THUMB_FACE_TILT)
            out = args.output or "left_hand.step"
        elif args.mode == "right":
            result = build_layout(2, args.fn_row, kc, key_angles=KEY_ANGLES, key_height=KEY_HEIGHT, key_face_tilt=KEY_FACE_TILT, thumb_sweep=THUMB_SWEEP, thumb_face_tilt=THUMB_FACE_TILT)
            out = args.output or "right_hand.step"
        else:
            result = build_layout(3, args.fn_row, kc, key_angles=KEY_ANGLES, key_height=KEY_HEIGHT, key_face_tilt=KEY_FACE_TILT, thumb_sweep=THUMB_SWEEP, thumb_face_tilt=THUMB_FACE_TILT)
            out = args.output or "ergohaven_full.step"

        if out.endswith(".stl"):
            export_stl(result, out)
        else:
            export_step(result, out)
        print("Done!")
    finally:
        _finalize_runtime_notes()
